// Textos do site da Aplysia, em português e inglês (o site atual tem as duas línguas, com bandeiras no topo).
// Tirados do site atual (aplysia.com.br) em 2026-10-09. Cada texto é [português, inglês].
// Onde o site atual tem a versão em inglês, ela foi usada; o resto foi traduzido.

export const site = {
  dominio: 'https://aplysia.overtus.com.br',
  nome: 'APLYSIA',
  razao: 'APLYSIA Assessoria e Consultoria Ltda.',
  desde: 1997,
  zap: '5527998394839',
  fones: [['(27) 3337-4877', '552733374877'], ['(27) 99839-4839', '5527998394839']],
  unidades: [
    {
      nome: ['Soluções em Ecotoxicologia', 'Ecotoxicology Solutions'],
      fone: ['(27) 3337-4877', '552733374877'],
      email: 'solucoes@aplysia.com.br',
      end: ['Av. Carlos Gomes de Sá, 335, Mata da Praia', 'Vitória/ES · CEP 29066-040'],
      mapa: 'https://www.google.com/maps/search/?api=1&query=Av.+Carlos+Gomes+de+S%C3%A1%2C+335%2C+Mata+da+Praia%2C+Vit%C3%B3ria+ES',
    },
    {
      nome: ['Laboratório de Ecotoxicologia', 'Ecotoxicology Laboratory'],
      fone: ['(27) 3068-5109', '552730685109'],
      email: 'laboratorio@aplysia.com.br',
      end: ['Rua Maria Delunardo Trancoso, 134, Bairro de Fátima', 'Serra/ES · CEP 29160-771'],
      mapa: 'https://www.google.com/maps/search/?api=1&query=Maria+Delunardo+Trancoso%2C+134%2C+Bairro+de+F%C3%A1tima%2C+Serra+ES',
    },
  ],
  redes: [
    ['Facebook', 'https://www.facebook.com/APLYSIAtecnologia'],
    ['Instagram', 'https://www.instagram.com/aplysiameioambiente/'],
    ['LinkedIn', 'https://www.linkedin.com/company/aplysia-tecnologia-para-o-meio-ambiente'],
    ['YouTube', 'https://www.youtube.com/@aplysiasolucoesambientais4099'],
  ],
};

// Segmentos: cores dos cartões do site atual (azul, laranja, verde, vermelho, roxo).
export const segmentos = [
  {
    slug: 'mineracao-siderurgia-metalurgia', cor: '#0e84b6', foto: 'seg-mineracao',
    nome: ['Mineração, Siderurgia e Metalurgia', 'Mining, Steel and Metallurgy'],
    frase: ['É possível entregar com pontualidade, sem faltar segurança e responsabilidade.', 'It is possible to deliver punctually, without losing security and responsibility.'],
    intro: ['A APLYSIA oferece serviços diversos para empresas do segmento de Siderurgia, Mineração e Metalurgia. Desde a orientação aos processos para o Licenciamento Ambiental, avaliações de riscos ambientais, monitoramentos de efluentes e treinamento de operadores. Confira abaixo a lista completa do que a APLYSIA pode fazer pela sua empresa, com a pontualidade que ela precisa.',
      'APLYSIA offers a wide range of services to companies in the Steel, Mining and Metallurgy sector, from guidance on Environmental Licensing processes to environmental risk assessments, effluent monitoring and operator training. Below is the complete list of what APLYSIA can do for your company, with the punctuality it needs.'],
    servicos: [
      ['Licenciamento Ambiental.', 'Environmental licensing.'],
      ['Gestão de condicionantes; assessoramento junto aos Órgãos de Controle.', 'Management of license conditions; support before the Regulatory Agencies.'],
      ['Elaboração de Termos de Referência e Planos de análises ambientais.', 'Preparation of Terms of Reference and environmental analysis plans.'],
      ['Avaliação do risco ambiental de insumos químicos usados no processo produtivo e na ETE.', 'Environmental risk assessment of chemical inputs used in the production process and in the effluent treatment plant (ETP).'],
      ['Avaliação do risco ambiental dos produtos a serem exportados pelo porto, em atendimento às diretrizes da IMO.', 'Environmental risk assessment of products to be exported through the port, in compliance with IMO guidelines.'],
      ['Mapeamento e balanço de carga química e tóxica de efluentes setoriais.', 'Mapping and balance of the chemical and toxic load of sector effluents.'],
      ['Monitoramento ecotoxicológico de efluentes.', 'Ecotoxicological monitoring of effluents.'],
      ['Estabelecimento de indicadores e limites de qualidade dos efluentes setoriais e efluente de entrada da ETE.', 'Definition of quality indicators and limits for sector effluents and ETP inlet effluent.'],
      ['Treinamentos customizados de sensibilização ambiental dos operadores da fábrica.', 'Customized environmental awareness training for plant operators.'],
      ['Treinamento técnico para operadores de ETEs.', 'Technical training for ETP operators.'],
      ['Start up, diagnóstico e monitoramento da microbiota da ETE.', 'Start-up, diagnosis and monitoring of the ETP microbiota.'],
      ['Definição da área de abrangência da pluma dos efluentes no ambiente.', 'Definition of the area covered by the effluent plume in the environment.'],
      ['Melhoria de performance da ETE e redução de custos.', 'ETP performance improvement and cost reduction.'],
      ['Cálculo do limite máximo de ecotoxicidade para efluente final tratado.', 'Calculation of the maximum ecotoxicity limit for treated final effluent.'],
      ['Identificação da causa e fonte de toxicidade do efluente, com soluções para sua redução/eliminação.', 'Identification of the cause and source of effluent toxicity, with solutions for its reduction or elimination.'],
      ['Implementação de sistemas de controle operacional da ETE.', 'Implementation of ETP operational control systems.'],
      ['Monitoramento ambiental de águas superficiais e subterrâneas, sedimentos e solos.', 'Environmental monitoring of surface water, groundwater, sediments and soils.'],
      ['Avaliação ecotoxicológica da água, sedimento e solos em atendimento às Resoluções CONAMA 420/2009, 430/2011 e 454/2012.', 'Ecotoxicological assessment of water, sediment and soils in compliance with CONAMA Resolutions 420/2009, 430/2011 and 454/2012.'],
      ['Monitoramentos de Fauna (Entomofauna, Anfíbios, Répteis, Aves e Mamíferos).', 'Fauna monitoring (insects, amphibians, reptiles, birds and mammals).'],
      ['Monitoramento de Flora Terrestre e Aquática.', 'Terrestrial and aquatic flora monitoring.'],
      ['Resgates de Fauna e Flora Terrestre, e Ictiofauna.', 'Rescue of terrestrial fauna and flora, and fish fauna.'],
      ['Monitoramento ativo e passivo de compostos bioacumuláveis.', 'Active and passive monitoring of bioaccumulative compounds.'],
      ['Avaliação do nível de contaminação da biota do entorno do empreendimento.', 'Assessment of the contamination level of the biota around the site.'],
      ['Avaliação crítica dos dados históricos de ecotoxicidade.', 'Critical review of historical ecotoxicity data.'],
      ['Integração de dados ambientais e desenvolvimento de indicadores gerenciais.', 'Integration of environmental data and development of management indicators.'],
      ['Análise do risco ecológico de rejeitos sólidos através de ensaios isolados e microcosmos.', 'Ecological risk analysis of solid waste through isolated tests and microcosms.'],
      ['Alternativas de remediação de sedimentos e solos.', 'Remediation alternatives for sediments and soils.'],
      ['Proposição de alternativas de mitigação, analisando os cenários de viabilidade social, ambiental e econômica.', 'Proposal of mitigation alternatives, analyzing social, environmental and economic feasibility scenarios.'],
      ['Elaboração de Plano Diretor de Biodiversidade.', 'Preparation of a Biodiversity Master Plan.'],
    ],
  },
  {
    slug: 'portos', cor: '#d97e09', foto: 'seg-portos',
    nome: ['Portos', 'Ports'],
    frase: ['Com inovação se vai ao longe. E seguindo o caminho certo.', 'Innovation leads the way. And following the right path.'],
    intro: ['Sua empresa é do segmento de Portos? A APLYSIA oferece uma gama de serviços de soluções ambientais, como Avaliação de Risco Ecológico, Gestão das Condicionantes Ambientais e Estudo para Licenciamento de Dragagens. Sua empresa pode ir mais longe com esses e muitos outros serviços da APLYSIA que você confere abaixo.',
      'Is your company in the Ports segment? APLYSIA offers a range of environmental solutions, such as Ecological Risk Assessment, Management of Environmental License Conditions and Studies for Dredging Licensing. Your company can go further with these and many other APLYSIA services listed below.'],
    servicos: [
      ['Estudo de caracterização do sedimento a ser dragado segundo CONAMA 454/2012.', 'Characterization study of the sediment to be dredged, according to CONAMA 454/2012.'],
      ['Realização dos ensaios ecotoxicológicos segundo CONAMA 454/2012.', 'Ecotoxicological testing according to CONAMA 454/2012.'],
      ['Simulação de dragagens em laboratório (elutriatos).', 'Laboratory dredging simulation (elutriates).'],
      ['Avaliação do risco ecológico da dragagem de sedimentos.', 'Ecological risk assessment of sediment dredging.'],
      ['Avaliação do potencial de bioacumulação dos contaminantes do sedimento na biota e indicação da destinação do material dragado.', 'Assessment of the bioaccumulation potential of sediment contaminants in the biota and recommendation for the destination of the dredged material.'],
      ['Elaboração de planilha de avaliação de impactos ambientais, impactos na pesca e impactos econômicos de cada alternativa de disposição.', 'Assessment spreadsheet of the environmental, fishing and economic impacts of each disposal alternative.'],
      ['Modelagem da pluma da dragagem.', 'Dredging plume modeling.'],
      ['Identificação da causa da toxicidade da fração líquida e sólida dos sedimentos segundo EPA-USA.', 'Identification of the cause of toxicity of the liquid and solid fractions of sediments, according to US EPA.'],
      ['Avaliação das possíveis alternativas de disposição do sedimento dragado.', 'Assessment of possible disposal alternatives for the dredged sediment.'],
      ['Determinação da concentração máxima de sedimento que poderá ser disposto sem causar danos ambientais.', 'Determination of the maximum sediment concentration that can be disposed of without environmental damage.'],
      ['Avaliação da área de disposição atual para verificar se a mesma poderá receber mais sedimento dragado.', 'Assessment of the current disposal area to verify whether it can receive more dredged sediment.'],
      ['Busca e avaliação de novas áreas de disposição no mar para o sedimento dragado.', 'Search and assessment of new offshore disposal areas for the dredged sediment.'],
      ['Avaliação das alternativas de disposição para o material dragado não aprovado pelo IBAMA.', 'Assessment of disposal alternatives for dredged material not approved by IBAMA.'],
      ['Estudo ambiental para Licenciamento de dragagens.', 'Environmental study for dredging licensing.'],
      ['Gestão das condicionantes ambientais.', 'Management of environmental license conditions.'],
      ['Desenvolvimento do Plano de Gerenciamento da Dragagem para assegurar menos impactos físicos, químicos e biológicos.', 'Development of the Dredging Management Plan to ensure fewer physical, chemical and biological impacts.'],
      ['Monitoramento ambiental da dragagem e da área de deposição do sedimento dragado.', 'Environmental monitoring of the dredging and of the dredged sediment disposal area.'],
      ['Avaliação ambiental da área de disposição do sedimento dragado.', 'Environmental assessment of the dredged sediment disposal area.'],
      ['Determinação do tempo de recuperação ambiental da área de disposição.', 'Determination of the environmental recovery time of the disposal area.'],
      ['Integração dos dados químicos e biológicos e determinação de indicadores gerenciais.', 'Integration of chemical and biological data and definition of management indicators.'],
      ['Alternativas de remediação de sedimentos e passivos ambientais.', 'Remediation alternatives for sediments and environmental liabilities.'],
      ['Monitoramento das atividades do porto.', 'Monitoring of port activities.'],
      ['Monitoramento ativo e passivo de compostos bioacumuláveis em tecido dos animais aquáticos e algas.', 'Active and passive monitoring of bioaccumulative compounds in the tissue of aquatic animals and algae.'],
      ['Avaliação do risco ambiental de produtos exportados via marítima segundo diretriz da IMO.', 'Environmental risk assessment of products exported by sea, according to IMO guidelines.'],
    ],
  },
  {
    slug: 'celulose-e-papel', cor: '#78981d', foto: 'seg-celulose',
    nome: ['Celulose e Papel', 'Pulp and Paper'],
    frase: ['Para criar raízes fortes, é preciso conduzir os trabalhos com transparência.', 'Performing tasks with transparency is the way to create strong roots.'],
    intro: ['A APLYSIA tem os profissionais certos para entregar soluções ambientais a empresas com raízes no segmento de Celulose e Papel. Por exemplo: se a sua empresa precisa de um Licenciamento Ambiental, a APLYSIA conhece todos os processos para adquiri-lo. Realiza ainda Gestão de Condicionantes e Melhoria de Performance de ETE. Abaixo você confere todas as nossas especialidades nessa área.',
      'APLYSIA has the right professionals to deliver environmental solutions to companies rooted in the Pulp and Paper sector. For example, if your company needs Environmental Licensing, APLYSIA knows every step of the process. We also handle Management of License Conditions and ETP Performance Improvement. Below are all our specialties in this area.'],
    servicos: [
      ['Licenciamento Ambiental.', 'Environmental licensing.'],
      ['Assessoramento ambiental de base preventiva na concepção do projeto industrial.', 'Preventive environmental advisory during the design of the industrial project.'],
      ['Gestão de condicionantes.', 'Management of license conditions.'],
      ['Avaliação do risco ambiental de insumos químicos usados no processo produtivo.', 'Environmental risk assessment of chemical inputs used in the production process.'],
      ['Balanço de carga química e tóxica de efluentes setoriais.', 'Chemical and toxic load balance of sector effluents.'],
      ['Monitoramento ecotoxicológico de efluentes.', 'Ecotoxicological monitoring of effluents.'],
      ['Estabelecimento de indicadores e limites de qualidade dos efluentes setoriais e efluente de entrada da ETE.', 'Definition of quality indicators and limits for sector effluents and ETP inlet effluent.'],
      ['Start up, diagnóstico e monitoramento da microbiota da ETE.', 'Start-up, diagnosis and monitoring of the ETP microbiota.'],
      ['Implementação de sistemas de controle operacional da ETE.', 'Implementation of ETP operational control systems.'],
      ['Melhoria de performance da ETE e redução de custos.', 'ETP performance improvement and cost reduction.'],
      ['Treinamentos customizados de sensibilização ambiental dos operadores da fábrica.', 'Customized environmental awareness training for plant operators.'],
      ['Treinamento técnico para operadores de ETEs.', 'Technical training for ETP operators.'],
      ['Cálculo do limite máximo de ecotoxicidade permissível para efluente final tratado.', 'Calculation of the maximum permissible ecotoxicity for treated final effluent.'],
      ['Identificação da causa e fonte de toxicidade do efluente, com soluções para sua redução/eliminação.', 'Identification of the cause and source of effluent toxicity, with solutions for its reduction or elimination.'],
      ['Monitoramento ambiental de águas superficiais e subterrâneas, sedimentos e solos.', 'Environmental monitoring of surface water, groundwater, sediments and soils.'],
      ['Monitoramento ativo e passivo de organoclorados através de bioindicadores.', 'Active and passive monitoring of organochlorines through bioindicators.'],
      ['Integração de dados ambientais e desenvolvimento de indicadores gerenciais.', 'Integration of environmental data and development of management indicators.'],
      ['Análise do risco ecológico de rejeitos sólidos.', 'Ecological risk analysis of solid waste.'],
      ['Elaboração de Plano Diretor de Biodiversidade.', 'Preparation of a Biodiversity Master Plan.'],
    ],
  },
  {
    slug: 'oleo-e-gas', cor: '#c11428', foto: 'seg-oleo',
    nome: ['Óleo e Gás', 'Oil and Gas'],
    frase: ['Competência técnica de quem conhece a fundo o que faz.', 'Technical competence of those with in-depth knowledge of what they do.'],
    intro: ['Confira abaixo o portfólio de serviços que a APLYSIA tem para oferecer a empresas do segmento de Óleo e Gás. Conhecemos a fundo e somos especializados em soluções ambientais, realizando serviços como Monitoramento, Instalação de Poços, Licenciamento Ambiental, Melhoria da Performance de ETE e muitos outros.',
      'Below is the portfolio of services APLYSIA offers to companies in the Oil and Gas sector. We know the field in depth and specialize in environmental solutions, providing services such as Monitoring, Well Installation, Environmental Licensing, ETP Performance Improvement and many others.'],
    servicos: [
      ['Monitoramento ambiental de águas continentais, costeiras e oceânicas.', 'Environmental monitoring of inland, coastal and ocean waters.'],
      ['Licenciamento Ambiental.', 'Environmental licensing.'],
      ['Avaliação integrada (bentos, química, ecotoxicidade) da qualidade ambiental do sedimento, gerando indicadores ambientais.', 'Integrated assessment (benthos, chemistry, ecotoxicity) of sediment environmental quality, generating environmental indicators.'],
      ['Monitoramento ecotoxicológico de efluentes, fluidos de perfuração, água produzida e amostras ambientais.', 'Ecotoxicological monitoring of effluents, drilling fluids, produced water and environmental samples.'],
      ['Monitoramento da colonização da estrutura fixa da plataforma por organismos bioincrustantes e fauna acompanhante.', 'Monitoring of the colonization of fixed platform structures by biofouling organisms and associated fauna.'],
      ['Monitoramento ativo do efluente usando moluscos como bioindicadores de hidrocarbonetos e metais.', 'Active effluent monitoring using mollusks as bioindicators of hydrocarbons and metals.'],
      ['Caracterização físico-química e ecotoxicológica da fração dispersa e fração solúvel de fluidos de perfuração, lama de perfuração, produtos químicos, petróleo, óleos e fração particulada suspensa de cascalho de perfuração.', 'Physicochemical and ecotoxicological characterization of the dispersed and soluble fractions of drilling fluids, drilling mud, chemicals, crude oil, oils and the suspended particulate fraction of drill cuttings.'],
      ['Avaliação dos dados ambientais históricos físico-químicos e biológicos.', 'Assessment of historical physicochemical and biological environmental data.'],
      ['Fiscalização de amostragem em campanhas oceanográficas.', 'Sampling supervision in oceanographic campaigns.'],
      ['Elaboração e execução de Programa de Educação Ambiental aos Trabalhadores (PEAT).', 'Design and execution of the Workers’ Environmental Education Program (PEAT).'],
      ['Estudo da ecologia de bentos do substrato não consolidado e costão em ambiente marinho e lacustre.', 'Study of benthic ecology on unconsolidated substrate and rocky shores in marine and lake environments.'],
      ['Melhoria de performance de ETEs.', 'ETP performance improvement.'],
      ['Elaboração de Plano Diretor de Biodiversidade.', 'Preparation of a Biodiversity Master Plan.'],
      ['Atendimento às condicionantes socioambientais.', 'Compliance with social and environmental license conditions.'],
      ['Instalação de poços de monitoramento multinível, coleta e análise de amostras de água desses poços e elaboração de mapas potenciométricos. Avaliação da flutuação sazonal da superfície freática e das relações entre as águas subterrâneas e as águas superficiais.', 'Installation of multilevel monitoring wells, collection and analysis of water samples from these wells and preparation of potentiometric maps. Assessment of seasonal water table fluctuation and of the relationship between groundwater and surface water.'],
    ],
  },
  {
    slug: 'outros-segmentos', cor: '#521d6b', foto: 'seg-outros',
    nome: ['Outros Segmentos', 'Other Segments'],
    frase: ['Deixe as demandas da sua empresa com quem tem reconhecimento e respeito do mercado.', 'Leave your corporate requirements to those who enjoy market acknowledgment and respect.'],
    intro: ['A APLYSIA também realiza trabalhos para setores como o Alimentício, Farmacêutico, Sucroalcooleiro e Químico, entregando soluções diversas para o controle das demandas ambientais dessas empresas. Veja abaixo a lista completa de serviços para os mais diversos setores industriais e conte com a APLYSIA para realizar projetos que avaliam, monitoram e mapeiam os riscos ambientais.',
      'APLYSIA also works for sectors such as Food, Pharmaceutical, Sugar and Ethanol, and Chemical, delivering a range of solutions to control the environmental demands of these companies. Below is the complete list of services for the most diverse industrial sectors. Count on APLYSIA for projects that assess, monitor and map environmental risks.'],
    servicos: [
      ['Licenciamento Ambiental.', 'Environmental licensing.'],
      ['Gestão de condicionantes; assessoramento junto aos Órgãos de Controle.', 'Management of license conditions; support before the Regulatory Agencies.'],
      ['Elaboração de Termos de Referência e Planos de análises ambientais.', 'Preparation of Terms of Reference and environmental analysis plans.'],
      ['Avaliação do risco ambiental de insumos químicos usados no processo produtivo e na ETE.', 'Environmental risk assessment of chemical inputs used in the production process and in the effluent treatment plant (ETP).'],
      ['Mapeamento e balanço de carga química e tóxica.', 'Mapping and balance of chemical and toxic load.'],
      ['Monitoramento ambiental (terrestre e aquático).', 'Environmental monitoring (terrestrial and aquatic).'],
      ['Resgate de fauna e flora.', 'Fauna and flora rescue.'],
      ['Atendimento às Resoluções CONAMA 420/2009, 430/2011, 454/2012 e outras.', 'Compliance with CONAMA Resolutions 420/2009, 430/2011, 454/2012 and others.'],
      ['Start up, diagnóstico e monitoramento da microbiota da ETE.', 'Start-up, diagnosis and monitoring of the ETP microbiota.'],
      ['Melhoria de performance da ETE e redução de custos.', 'ETP performance improvement and cost reduction.'],
      ['Treinamentos de sensibilização ambiental para operadores.', 'Environmental awareness training for operators.'],
      ['Avaliação ecotoxicológica de rejeitos, amostras ambientais e produtos químicos.', 'Ecotoxicological assessment of waste, environmental samples and chemicals.'],
      ['Identificação da causa e fonte de toxicidade do efluente, com soluções para sua redução/eliminação.', 'Identification of the cause and source of effluent toxicity, with solutions for its reduction or elimination.'],
      ['Integração de dados ambientais e desenvolvimento de indicadores ambientais.', 'Integration of environmental data and development of environmental indicators.'],
      ['Elaboração de Plano Diretor de Biodiversidade.', 'Preparation of a Biodiversity Master Plan.'],
    ],
  },
];

// Áreas de atuação, com os serviços de cada uma (título, frase do site atual e foto).
export const areas = [
  {
    slug: 'estudos-ambientais', foto: 's-termos', icone: 'doc',
    nome: ['Estudos Ambientais', 'Environmental Studies'],
    resumo: ['Licenciamento, Termos de Referência e gestão de condicionantes.', 'Licensing, Terms of Reference and management of license conditions.'],
    intro: [
      ['Tudo que sua empresa precisa para soluções ambientais, pode contar com a expertise da APLYSIA. Temos profissionais capacitados que conhecem todos os processos de Licenciamento Ambiental, Estudos Ambientais para Elaboração de Termos de Referência e Planos de Análises Ambientais, além de outros serviços.', 'Whatever your company needs in environmental solutions, it can count on APLYSIA’s expertise. Our qualified professionals know every step of Environmental Licensing, Environmental Studies for the preparation of Terms of Reference and Environmental Analysis Plans, among other services.'],
      ['Os Termos de Referência são protocolos técnicos exigíveis pelos Órgãos de Controle para subsidiar autorizações para Estudos de Impactos Ambientais e Licenciamentos (Autorizações). E, se necessário, a APLYSIA vai acompanhar a sua empresa junto aos órgãos de Controle Ambiental, prestando a devida assessoria técnica.', 'Terms of Reference are technical protocols required by the Regulatory Agencies to support authorizations for Environmental Impact Studies and Licensing. When needed, APLYSIA will represent your company before the environmental agencies, providing the necessary technical support.'],
      ['Temos em nossa história projetos realizados para 15 estados brasileiros e diversos países.', 'Our history includes projects carried out in 15 Brazilian states and several countries.'],
    ],
    servicos: [
      ['s-licenciamento', ['Licenciamento Ambiental', 'Environmental Licensing'], ['Conhecimento dos processos para sua empresa adquirir o Licenciamento Ambiental.', 'Knowledge of the processes for your company to obtain Environmental Licensing.']],
      ['s-termos', ['Elaboração de Termos de Referência e Planos de Análises Ambientais', 'Terms of Reference and Environmental Analysis Plans'], ['Sua empresa precisa e pode ganhar tempo na hora de fazer um estudo ambiental.', 'Your company needs to, and can, save time when carrying out an environmental study.']],
      ['s-condicionantes', ['Gestão de condicionantes e assessoramento junto aos Órgãos de Controle', 'Management of license conditions and support before Regulatory Agencies'], ['A APLYSIA oferece todo apoio que sua empresa precisa para atuar junto aos Órgãos de Controle Ambiental.', 'APLYSIA provides all the support your company needs before the Environmental Regulatory Agencies.']],
    ],
  },
  {
    slug: 'monitoramento', foto: 's-monit-ambiental', icone: 'onda',
    nome: ['Monitoramento', 'Monitoring'],
    resumo: ['Terrestre, aquático e oceanográfico, com relatórios gerenciais.', 'Terrestrial, aquatic and oceanographic, with management reports.'],
    intro: [
      ['O controle ambiental requer acompanhamento de acordo com indicadores técnico-científicos e legais. Este estudo inclui também o monitoramento do que é descartado no meio ambiente, através da avaliação de resíduos e efluentes.', 'Environmental control requires follow-up according to technical, scientific and legal indicators. This includes monitoring what is discharged into the environment, through the assessment of waste and effluents.'],
      ['A APLYSIA pode oferecer diferentes monitoramentos, como também analisar e recomendar ações de melhoria e minimização, se for o caso, integrando as informações em relatórios gerenciais, de muito boa comunicação com os gestores e órgãos de controle.', 'APLYSIA offers different types of monitoring and can also analyze and recommend improvement and minimization actions when needed, integrating the information into management reports that communicate clearly with managers and regulatory agencies.'],
      ['Realizamos também um monitoramento especial, segundo o Protocolo de Monitoramento de Efeitos Ambientais (2015), utilizado para monitoramento de efluentes e enquadramento de recursos hídricos na América do Norte e Europa.', 'We also carry out special monitoring under the Environmental Effects Monitoring Protocol (2015), used for effluent monitoring and water resource classification in North America and Europe.'],
      ['Atuamos na verificação da conformidade das operações de sua empresa com os limites legais definidos pelas Resoluções CONAMA referentes ao solo, qualidade da água, efluentes e dragagem. Para estudos de resgate de fauna e flora que devam ser protegidos, a APLYSIA também está capacitada para realizar este trabalho.', 'We verify that your company’s operations comply with the legal limits set by the CONAMA Resolutions for soil, water quality, effluents and dredging. APLYSIA is also qualified to carry out the rescue of fauna and flora that must be protected.'],
    ],
    servicos: [
      ['s-monit-ambiental', ['Monitoramento Ambiental (terrestre e aquático)', 'Environmental Monitoring (terrestrial and aquatic)'], ['Monitoramento ambiental de forma integrada e entrega da solução para sua empresa.', 'Integrated environmental monitoring and delivery of the solution for your company.']],
      ['s-bioacumulaveis', ['Monitoramento ativo e passivo de compostos bioacumuláveis', 'Active and passive monitoring of bioaccumulative compounds'], ['Avalie a qualidade do corpo receptor do efluente de sua empresa com o uso de bioindicadores e substitua inúmeras análises químicas feitas na água.', 'Assess the quality of the water body receiving your company’s effluent with bioindicators, replacing numerous chemical analyses of the water.']],
      ['s-resgate', ['Resgate de Fauna e Flora', 'Fauna and Flora Rescue'], ['O resgate de fauna e flora que as indústrias precisam antes de começar as suas atividades.', 'The fauna and flora rescue industries need before starting their activities.']],
      ['s-conama', ['Atendimento às Resoluções CONAMA 357/2005, 420/2009, 430/2011, 454/2012 e outras', 'Compliance with CONAMA Resolutions 357/2005, 420/2009, 430/2011, 454/2012 and others'], ['A APLYSIA pode assessorar em questões ligadas ao controle ambiental de sua empresa.', 'APLYSIA can advise on matters related to your company’s environmental control.']],
      ['s-oceanografico', ['Monitoramento Oceanográfico', 'Oceanographic Monitoring'], ['Alta performance em monitoramento físico, químico, biológico e geológico no ambiente marinho.', 'High performance in physical, chemical, biological and geological monitoring of the marine environment.']],
    ],
  },
  {
    slug: 'efluentes', foto: 's-ete-diagnostico', icone: 'gota',
    nome: ['Tratamento de Efluentes', 'Effluent Treatment'],
    titulo: ['Tratamento de Efluentes industriais e domésticos', 'Industrial and Domestic Effluent Treatment'],
    resumo: ['Diagnóstico, start up e performance da ETE, com redução de custos.', 'ETP diagnosis, start-up and performance, with cost reduction.'],
    intro: [
      ['Mesmo as empresas de médio e pequeno porte devem tratar os efluentes do processo industrial (efluentes industriais) e os gerados pelo seu pessoal (efluentes domésticos), para assegurar que o lançamento nos corpos d’água atenda aos padrões de qualidade legais. Para tanto é preciso contínua avaliação e acertada interpretação, de forma a atender às exigências da sociedade e racionalizar os custos operacionais.', 'Even small and medium-sized companies must treat the effluents from their industrial process (industrial effluents) and those generated by their staff (domestic effluents), to ensure that discharges into water bodies meet legal quality standards. This requires continuous assessment and accurate interpretation, meeting society’s demands while rationalizing operating costs.'],
      ['A APLYSIA, através de seus biólogos e laboratórios especializados, pode realizar toda a avaliação microbiológica (saúde da microbiota: bactérias do lodo, protozoários e metazoários) e de controle do processo do tratamento, com identificação de eventuais causas de queda de desempenho, proposição de soluções e ainda com redução de custos.', 'Through its biologists and specialized laboratories, APLYSIA carries out the full microbiological assessment (microbiota health: sludge bacteria, protozoa and metazoa) and treatment process control, identifying causes of performance loss, proposing solutions and reducing costs.'],
    ],
    servicos: [
      ['s-ete-monitoramento', ['Monitoramento de Estação de Tratamento de Efluentes', 'Effluent Treatment Plant Monitoring'], ['Avaliação e interpretação das causas da queda de performance das estações de tratamento de efluentes.', 'Assessment and interpretation of the causes of performance loss in effluent treatment plants.']],
      ['s-ete-diagnostico', ['Diagnóstico de Estação de Tratamento de Efluentes', 'Effluent Treatment Plant Diagnosis'], ['Estudo microbiológico para solucionar desempenho ineficaz das estações.', 'Microbiological study to solve ineffective plant performance.']],
      ['s-ete-startup', ['Start up de Estação de Tratamento de Efluentes', 'Effluent Treatment Plant Start-up'], ['É preciso competência técnica para a ETE da sua empresa funcionar perfeitamente.', 'It takes technical competence for your company’s ETP to work perfectly.']],
      ['s-ete-performance', ['Melhoria de Performance da ETE e Redução de Custos', 'ETP Performance Improvement and Cost Reduction'], ['Como está a ETE da sua empresa? Para uma melhor performance com redução de custos, conte com a APLYSIA.', 'How is your company’s ETP doing? For better performance at lower cost, count on APLYSIA.']],
      ['s-ete-treinamento', ['Treinamento para Operadores da ETE', 'Training for ETP Operators'], ['Quanto mais os operadores souberem de microbiologia, melhor para prevenirem impactos na ETE.', 'The more operators know about microbiology, the better they can prevent impacts on the ETP.']],
    ],
  },
  {
    slug: 'ecotoxicologia', foto: 's-daphnia', icone: 'lab',
    nome: ['Ecotoxicologia', 'Ecotoxicology'],
    titulo: ['Laboratório de Ecotoxicologia', 'Ecotoxicology Laboratory'],
    resumo: ['Laboratório próprio, acreditado pela ABNT NBR ISO/IEC 17025.', 'In-house laboratory, accredited to ABNT NBR ISO/IEC 17025.'],
    intro: [
      ['Com equipe especializada e laboratório próprio para análises ecotoxicológicas, a APLYSIA vem atendendo aos mais diversos setores da atividade econômica, subsidiando os seus gestores com instrumentos de mais agilidade, resolutividade e assertividade.', 'With a specialized team and its own laboratory for ecotoxicological analyses, APLYSIA serves the most diverse sectors of the economy, giving managers tools for greater agility, problem-solving and assertiveness.'],
      ['Deseja saber se o efluente produzido por uma empresa é tóxico, conhecer o grau de toxicidade de um produto químico ou ainda descobrir se água ou sedimento estão contaminados? Tudo isso é possível por meio de testes de toxicidade específicos realizados pela APLYSIA, alguns já previstos na legislação brasileira e exigidos por empresas socialmente responsáveis. No final, saem ganhando empresa, meio ambiente e sociedade.', 'Do you want to know whether an effluent is toxic, how toxic a chemical product is, or whether water or sediment is contaminated? All of this is possible through specific toxicity tests performed by APLYSIA, some already required by Brazilian legislation and demanded by socially responsible companies. In the end, the company, the environment and society all win.'],
    ],
    servicos: [
      ['s-daphnia', ['Ensaios ecotoxicológicos', 'Ecotoxicological tests'], ['Conheça os ensaios ecotoxicológicos realizados pela APLYSIA, com o maior número de ensaios acreditados no Brasil.', 'The ecotoxicological tests performed by APLYSIA, with the largest number of accredited tests in Brazil.']],
      ['s-insumos', ['Avaliação do Risco Ambiental de Insumos Químicos usados no Processo Produtivo e na ETE', 'Environmental Risk Assessment of Chemical Inputs used in the Production Process and in the ETP'], ['Um serviço para prevenir acidentes ambientais e suas consequências.', 'A service to prevent environmental accidents and their consequences.']],
      ['s-rejeitos', ['Avaliação Ecotoxicológica de Rejeitos, Amostras Ambientais e Produtos Químicos', 'Ecotoxicological Assessment of Waste, Environmental Samples and Chemicals'], ['Uma análise precisa em busca de potenciais danos aos ambientes da sua empresa.', 'A precise analysis in search of potential damage to your company’s environments.']],
    ],
  },
  {
    slug: 'restauro-fluvial', foto: 'rio-equipe', icone: 'rio',
    nome: ['Restauro Fluvial', 'River Restoration'],
    resumo: ['Renaturalização de córregos e rios com o método ReNaturalize.', 'Renaturalization of streams and rivers with the ReNaturalize method.'],
    destaque: ['Restauração e recuperação de rios. Um trabalho que modifica de forma positiva todo o ambiente em volta da sua empresa.', 'River restoration and recovery. Work that positively changes the entire environment around your company.'],
    intro: [
      ['Instituições públicas e empresas têm se voltado, mais e mais, para a recuperação dos recursos hídricos. A APLYSIA desenvolve e aplica técnicas de renaturalização de córregos e rios, com ganhos relevantes na redução dos sedimentos, no controle de enchentes e na restauração da biota local.', 'Public institutions and companies are increasingly turning to the recovery of water resources. APLYSIA develops and applies stream and river renaturalization techniques, with significant gains in sediment reduction, flood control and restoration of the local biota.'],
      ['Concomitantemente às ações de reflorestamento da mata ciliar, a renaturalização dos rios possibilita a recuperação das margens, aumentando a sua capacidade de estoque de água, de forma a regular a sua vazão.', 'Combined with the reforestation of riparian forests, river renaturalization allows the banks to recover, increasing water storage capacity and helping to regulate the flow.'],
    ],
    servicos: [],
    videos: ['ykhpOazjj54', 'NpM7vkX3UT4', 'gDv9jG8g9gI', 'nlFMrmI8DRo', 'pdgyVisRuW4', 'qTfugU241YA'],
  },
  {
    slug: 'solucoes-ambientais', foto: 's-integracao', icone: 'mapa',
    nome: ['Soluções Ambientais', 'Environmental Solutions'],
    titulo: ['Soluções Ambientais e Especialidades', 'Environmental Solutions and Specialties'],
    resumo: ['Carga tóxica, biodiversidade, passivos e auditoria de monitoramentos.', 'Toxic load, biodiversity, liabilities and monitoring audits.'],
    intro: [
      ['A APLYSIA trabalha com segurança e responsabilidade para realizar serviços em soluções ambientais, como mapeamento e balanço de carga química e tóxica ou identificação de causa e fonte da toxicidade dos efluentes. Realizamos trabalhos nessa área em mais de 15 estados brasileiros e diversos países.', 'APLYSIA works safely and responsibly to deliver environmental solutions such as chemical and toxic load mapping and balance, or identification of the cause and source of effluent toxicity. We have carried out work in this area in more than 15 Brazilian states and several countries.'],
    ],
    servicos: [
      ['s-integracao', ['Integração de dados ambientais e desenvolvimento de indicadores ambientais', 'Integration of environmental data and development of environmental indicators'], ['Sua empresa não vai mais perder tempo com os relatórios de análises ambientais inconclusivas.', 'Your company will no longer waste time on inconclusive environmental analysis reports.']],
      ['s-carga-toxica', ['Mapeamento e Balanço de Carga Química e Tóxica', 'Chemical and Toxic Load Mapping and Balance'], ['Vários efluentes tóxicos e uma causa: mapeamento da carga tóxica de efluentes.', 'Several toxic effluents and one cause: mapping the toxic load of effluents.']],
      ['s-toxicidade', ['Identificação da Causa e Fonte de Toxicidade dos Efluentes, com Soluções para sua Redução/Eliminação', 'Identification of the Cause and Source of Effluent Toxicity, with Solutions for its Reduction or Elimination'], ['Qual o composto químico está levando toxicidade para o seu efluente? A APLYSIA tem o serviço certo para descobrir.', 'Which chemical compound is making your effluent toxic? APLYSIA has the right service to find out.']],
      ['s-sensibilizacao', ['Treinamentos de Sensibilização Ambiental para Operadores', 'Environmental Awareness Training for Operators'], ['Prevenir é melhor do que remediar. Conscientize os empregados da sua empresa sobre os ganhos de se trabalhar em um ambiente equilibrado.', 'Prevention is better than cure. Make your employees aware of the gains of working in a balanced environment.']],
      ['s-biodiversidade', ['Elaboração de Plano Diretor de Biodiversidade', 'Biodiversity Master Plan'], ['A APLYSIA e a sua empresa trabalhando juntas a favor da biodiversidade.', 'APLYSIA and your company working together for biodiversity.']],
      ['s-exportados', ['Avaliação do risco ambiental de produtos exportados via marítima', 'Environmental risk assessment of products exported by sea'], ['A APLYSIA identifica o potencial tóxico de cargas que possam vir a ser lançadas no mar.', 'APLYSIA identifies the toxic potential of cargo that could be released into the sea.']],
      ['s-auditoria', ['Auditoria em monitoramentos', 'Monitoring audits'], ['A APLYSIA possui a equipe certa para ajudá-lo!', 'APLYSIA has the right team to help you.']],
      ['s-passivos', ['Avaliação do risco ambiental de Passivos e alternativas de remediação', 'Environmental risk assessment of liabilities and remediation alternatives'], ['A APLYSIA pode identificar qual a melhor opção para a gestão de seu passivo.', 'APLYSIA can identify the best option for managing your liability.']],
    ],
  },
];

export const quemSomos = [
  ['Uma empresa que acredita no que faz. E faz com competência e responsabilidade. Uma empresa que acredita no progresso sustentável e que toda forma de vida e o meio ambiente merecem ser protegidos e preservados. Uma empresa que une tradição e inovação em tudo que faz.', 'A company that believes in what it does, and does it with competence and responsibility. A company that believes in sustainable progress and that every form of life and the environment deserve to be protected and preserved. A company that combines tradition and innovation in everything it does.'],
  ['E por falar em inovação, executamos projetos utilizando as mais modernas técnicas e metodologias de aceitação mundial. Também implantamos soluções personalizadas e desenvolvemos pesquisas para biomonitoramento e controles ambientais, atuando em 15 estados brasileiros e diversos países.', 'Speaking of innovation, we carry out projects using the most modern, internationally accepted techniques and methodologies. We also implement customized solutions and conduct research on biomonitoring and environmental control, working in 15 Brazilian states and several countries.'],
  ['E essa história começou há bastante tempo. Desde 1997, desenvolvemos soluções completas para a indústria. Somos especialistas em avaliação ambiental, atuando na identificação da causa e dos efeitos de impactos em ambientes, além de possuirmos know-how na identificação, análise e apresentação de soluções que trazem ganhos de eficiência e redução de custos para as empresas.', 'This story began a long time ago. Since 1997, we have developed complete solutions for industry. We are specialists in environmental assessment, identifying the causes and effects of impacts on the environment, with the know-how to identify, analyze and present solutions that bring efficiency gains and cost reductions to companies.'],
  ['Para isto, a APLYSIA conta com um quadro de profissionais altamente qualificado nas áreas de engenharia, biologia, oceanografia, geologia, ecologia, além de uma rede internacional de consultores especializados, para planejar, monitorar, avaliar e licenciar atividades industriais, de dragagem, de gestão ambiental hídrica e de solos, entre outros.', 'To this end, APLYSIA has a highly qualified team in engineering, biology, oceanography, geology and ecology, as well as an international network of specialized consultants, to plan, monitor, assess and license industrial and dredging activities, water and soil environmental management, among others.'],
  ['Contamos com laboratório próprio para análises microbiológicas e ecotoxicológicas, acreditado pela NBR ISO 17.025, e temos atendido aos mais diversos setores da atividade econômica, subsidiando os seus gestores com instrumentos de mais agilidade, resolutividade e assertividade.', 'We have our own laboratory for microbiological and ecotoxicological analyses, accredited to NBR ISO 17025, and we serve the most diverse sectors of the economy, giving their managers tools for greater agility, problem-solving and assertiveness.'],
  ['Somos capazes de fazer o melhor para a sua empresa, com diferentes soluções e prezando sempre pela excelência. Se você deseja tranquilidade, conte conosco.', 'We are able to do our best for your company, with different solutions and always striving for excellence. If you want peace of mind, count on us.'],
];

export const missao = ['Oferecer tranquilidade através de projetos de soluções ambientais customizadas de recursos hídricos, monitorando e assegurando seus resultados e entregas com competência, responsabilidade e confiabilidade.', 'To offer peace of mind through customized environmental solution projects for water resources, monitoring and ensuring their results and deliveries with competence, responsibility and reliability.'];
export const visao = ['Ser líder na superação dos desafios ambientais de seus clientes.', 'To be the leader in overcoming our clients’ environmental challenges.'];
export const valores = [
  [['Acreditar', 'Believe'], ['Acreditamos no que fazemos.', 'We believe in what we do.']],
  [['Impactar', 'Impact'], ['Gerar impacto positivo em todas as nossas ações.', 'Create a positive impact in all our actions.']],
  [['Padronizar', 'Standardize'], ['Estabelecer padrões em normalização.', 'Set standards in normalization.']],
  [['Aprimorar', 'Improve'], ['Unir tradição e inovação para desenvolver ou melhorar produtos, processos e sistemas.', 'Combine tradition and innovation to develop or improve products, processes and systems.']],
  [['Antever', 'Anticipate'], ['Entender os momentos vividos pelos clientes e adequar soluções a eles.', 'Understand the moments our clients are going through and tailor solutions to them.']],
  [['Sermos assertivos', 'Be assertive'], ['Assertividade gerencial, tecnicamente correta, transparente, mensurável e confidencial.', 'Management assertiveness: technically correct, transparent, measurable and confidential.']],
  [['Cocriar', 'Co-create'], ['Atender em parceria com os nossos clientes.', 'Work in partnership with our clients.']],
  [['Mobilizar', 'Mobilize'], ['Mobilização especializada e imediata, com logística just in time e atuação em campo.', 'Specialized, immediate mobilization, with just-in-time logistics and field work.']],
  [['Liderar', 'Lead'], ['Liderança tecnológica premiada.', 'Award-winning technological leadership.']],
];

// Etapas de atuação, tiradas do texto do site atual ("planejar, monitorar, avaliar e licenciar").
export const etapas = [
  [['Planejar', 'Plan'], ['Termos de Referência, planos de análises e assessoria preventiva desde a concepção do projeto.', 'Terms of Reference, analysis plans and preventive advisory from the project design stage.']],
  [['Monitorar', 'Monitor'], ['Água, sedimento, solo, efluentes, fauna e flora, em terra e no mar.', 'Water, sediment, soil, effluents, fauna and flora, on land and at sea.']],
  [['Avaliar', 'Assess'], ['Ensaios ecotoxicológicos acreditados, risco ecológico e causa da toxicidade.', 'Accredited ecotoxicological tests, ecological risk and cause of toxicity.']],
  [['Licenciar', 'License'], ['Licenciamento ambiental e gestão de condicionantes junto aos órgãos de controle.', 'Environmental licensing and management of license conditions before the regulatory agencies.']],
];

export const premios = [
  [2023, ['Best Paper 2023', 'Best Paper 2023'], ['SETAC e editores do IEAM', 'SETAC and IEAM editors'], ['Artigo “Short-term hydromorphological and ecological responses of using woody structures for river restoration in a tailing-impacted tropical river”, feito com a Fundação Renova.', 'Paper “Short-term hydromorphological and ecological responses of using woody structures for river restoration in a tailing-impacted tropical river”, written with Fundação Renova.']],
  [2022, ['XII Prêmio Hugo Werneck de Meio Ambiente, Sustentabilidade & Amor à Natureza', 'XII Hugo Werneck Award for Environment, Sustainability & Love of Nature'], ['Melhor Exemplo em Água', 'Best Example in Water'], ['Projeto ReNaturalize, técnica de biorremediação para renaturalização de rios.', 'ReNaturalize project, a bioremediation technique for river renaturalization.']],
  [2021, ['BRICS Solutions for SDGs Awards', 'BRICS Solutions for SDGs Awards'], ['BRICS Business Council', 'BRICS Business Council'], ['Única empresa brasileira entre as vencedoras, com o ReNaturalize na categoria ODS 6 (água potável e saneamento).', 'The only Brazilian company among the winners, with ReNaturalize in the SDG 6 category (clean water and sanitation).']],
  [2021, ['Prêmio Referência 2021', 'Referência Award 2021'], ['Grupo Referência', 'Grupo Referência'], ['Entre os 10 maiores destaques em serviços para os setores industrial, madeireiro, florestal, de celulose e papel e biomassa.', 'Among the top 10 highlights in services for the industrial, timber, forestry, pulp and paper and biomass sectors.']],
  [2020, ['Melhor Trabalho da Sessão Técnica de Meio Ambiente', 'Best Paper, Environment Technical Session'], ['ABTCP, 53º Congresso Internacional de Celulose e Papel', 'ABTCP, 53rd International Pulp and Paper Congress'], ['Estudo “Estudos de linha de base como ferramenta de gestão de risco”.', 'Study “Baseline studies as a risk management tool”.']],
  [2016, ['1º lugar, Inovação em Soluções de Gestão da Água (foco empresarial)', '1st place, Innovation in Water Management Solutions (business focus)'], ['Prêmio Ecologia', 'Ecology Award'], ['Projeto ReNaturalize.', 'ReNaturalize project.']],
  [2015, ['Melhor Trabalho da Sessão Técnica de Meio Ambiente', 'Best Paper, Environment Technical Session'], ['ABTCP, 48º Congresso Internacional de Celulose e Papel', 'ABTCP, 48th International Pulp and Paper Congress'], ['Estudo sobre o efeito da condutividade no tratamento biológico de efluente de fábrica de celulose.', 'Study on the effect of conductivity on the biological treatment of pulp mill effluent.']],
  [2015, ['Homenagem, categoria empresa privada', 'Tribute, private company category'], ['Secretaria Estadual de Ciência e Tecnologia', 'State Secretariat of Science and Technology'], ['Contribuição à ciência, tecnologia e inovação com projetos sustentáveis e aplicáveis.', 'Contribution to science, technology and innovation with sustainable, applicable projects.']],
  [2015, ['3º lugar, Categoria Pesquisa, 15º Prêmio Ecologia', '3rd place, Research Category, 15th Ecology Award'], ['Prêmio Ecologia', 'Ecology Award'], ['Projeto ReNaturalize como solução para a restauração de corpos d’água.', 'ReNaturalize project as a solution for restoring water bodies.']],
  [2014, ['Melhor Trabalho da Sessão Técnica de Meio Ambiente', 'Best Paper, Environment Technical Session'], ['ABTCP', 'ABTCP'], ['Estudo sobre causas e consequências do bulking viscoso em lodo de estação de tratamento de efluentes.', 'Study on the causes and consequences of viscous bulking in effluent treatment plant sludge.']],
  [2013, ['1º Prêmio Melhores Fornecedores, Serviços Técnicos Especializados', '1st Best Suppliers Award, Specialized Technical Services'], ['PETROBRAS', 'PETROBRAS'], ['Unidade de produção da Petrobras no Rio Grande do Norte e Ceará.', 'Petrobras production unit in Rio Grande do Norte and Ceará.']],
  [2010, ['1º lugar, Capixabas do Ano, Empresário do Ano', '1st place, Capixabas of the Year, Business Person of the Year'], ['A Gazeta', 'A Gazeta'], ['Reconhecimento na categoria empresário.', 'Recognition in the business person category.']],
  [2008, ['1º lugar, Prêmio MPE Brasil, Espírito Santo (Serviços)', '1st place, MPE Brasil Award, Espírito Santo (Services)'], ['MPE Brasil', 'MPE Brasil'], ['Reconhecimento na categoria serviços.', 'Recognition in the services category.']],
  [2008, ['1º lugar, Prêmio Pau-Brasil de Meio Ambiente', '1st place, Pau-Brasil Environment Award'], ['ABTCP, 41º Congresso', 'ABTCP, 41st Congress'], ['Prêmio ambiental do congresso internacional de celulose e papel.', 'Environmental award of the international pulp and paper congress.']],
  [2006, ['1º lugar, Prêmio Meio Ambiente', '1st place, Environment Award'], ['ABTCP-TAPPI, 39º Congresso', 'ABTCP-TAPPI, 39th Congress'], ['Prêmio ambiental do congresso internacional de celulose e papel.', 'Environmental award of the international pulp and paper congress.']],
  [2003, ['1º lugar, Prêmio Meio Ambiente', '1st place, Environment Award'], ['ABTCP-TAPPI, 36º Congresso', 'ABTCP-TAPPI, 36th Congress'], ['Prêmio ambiental do congresso internacional de celulose e papel.', 'Environmental award of the international pulp and paper congress.']],
  [2001, ['1º lugar, Trabalho de Maior Aplicabilidade Prática', '1st place, Work of Greatest Practical Applicability'], ['Sindicato da Indústria do Papel, Celulose e Pasta de Madeira do Estado de São Paulo', 'São Paulo State Pulp, Paper and Wood Pulp Industry Union'], ['Reconhecimento pela aplicabilidade prática do trabalho.', 'Recognition of the work’s practical applicability.']],
  [1997, ['1º lugar, Prêmio Tião de Sá', '1st place, Tião de Sá Award'], ['Secretaria Municipal de Meio Ambiente de Vitória-ES', 'Vitória-ES Municipal Environment Secretariat'], ['Prêmio ambiental municipal.', 'Municipal environmental award.']],
  [1997, ['1º lugar, Prêmio Mérito', '1st place, Merit Award'], ['ABTCP', 'ABTCP'], ['Prêmio da Associação Brasileira Técnica de Celulose e Papel.', 'Award from the Brazilian Pulp and Paper Technical Association.']],
];

const C = 'https://www.aplysia.com.br/pt/empresa/casos-de-sucesso/';
export const casos = [
  [2020, ['Análise de Dados desenvolvida pela Aplysia otimiza estudos ambientais em fábrica de celulose', 'Data analysis developed by Aplysia optimizes environmental studies at a pulp mill'], 'celulose-e-papel', C + '14-analise-de-dados-desenvolvida-pela-aplysia-otimiza-estudos-ambientais-em-fabrica-de-celulose/'],
  [2018, ['Estudo sobre celulose microfibrilada comprova que a substância não agrega toxicidade ao efluente industrial', 'Study on microfibrillated cellulose proves the substance adds no toxicity to industrial effluent'], 'celulose-e-papel', C + '16-aplysia-apresenta-estudo-sobre-celulose-microfibrilada-que-comprova-que-a-substancia-nao-agrega-toxicidade-ao-efluente-industrial/'],
  [2017, ['Indicadores biológicos como ferramenta de monitoramento ambiental: case em fábrica de celulose', 'Biological indicators as an environmental monitoring tool: a pulp mill case'], 'celulose-e-papel', C + '15-aplysia-comprova-que-os-indicadores-biologicos-sao-excelentes-ferramentas-no-monitoramento-ambiental-com-case-em-fabrica-de-celulose/'],
  [2017, ['Como o setor de celulose e papel atende os padrões ecotoxicológicos de efluentes', 'How the pulp and paper sector meets effluent ecotoxicological standards'], 'celulose-e-papel', C + '17-estudo-da-aplysia-mostra-como-o-setor-de-celulose-e-papel-atende-os-padroes-ecotoxicologicos-de-efluentes/'],
  [2016, ['Avaliação histórica da ecotoxicidade nas lagoas internas de um complexo siderúrgico no Espírito Santo', 'Historical assessment of ecotoxicity in the internal ponds of a steel complex in Espírito Santo'], 'mineracao-siderurgia-metalurgia', C + '10-avaliacao-historica-da-ecotoxicidade-nas-lagoas-internas-de-um-complexo-siderurgico-no-estado-do-espirito-santo/'],
  [2016, ['Aplicação da tríade em avaliação temporal de uma área de bota-fora', 'Applying the triad in a temporal assessment of a disposal area'], 'portos', C + '12-aplicacao-da-triade-em-avaliacao-temporal-de-uma-area-de-bota-fora/'],
  [2016, ['Qualidade química do sedimento em área sob influência da disposição de material dragado para implantação de um estaleiro', 'Chemical quality of sediment in an area influenced by dredged material disposal for a shipyard'], 'portos', C + '13-avaliacao-quimica-da-qualidade-do-sedimento-em-uma-area-sobre-influenciada-da-disposicao-do-material-dragado-para-implantacao-de-um-estaleiro/'],
  [2015, ['Variação espacial da macrofauna bentônica do estuário do rio Benevente, Anchieta-ES', 'Spatial variation of benthic macrofauna in the Benevente river estuary, Anchieta-ES'], 'outros-segmentos', C + '2-variacao-espacial-da-macrofauna-bentonica-do-estuario-do-rio-benevente-anchieta-es/'],
  [2015, ['Causas e consequências do bulking viscoso em lodo biológico de ETE de fábrica de celulose', 'Causes and consequences of viscous bulking in biological sludge at a pulp mill ETP'], 'celulose-e-papel', C + '9-causas-e-consequencias-da-formacao-do-bulking-viscoso-em-lodo-biologico-de-uma-ete-de-fabrica-de-celulose/'],
  [2014, ['Ensaios ecotoxicológicos na avaliação da qualidade ambiental de sedimentos marinhos', 'Ecotoxicological tests in assessing the environmental quality of marine sediments'], 'portos', C + '1-a-utilizacao-de-ensaios-ecotoxicologicos-como-forma-de-auxiliar-na-avaliacao-da-qualidade-ambiental-de-sedimentos-marinhos/'],
  [2014, ['Solos com baixas intervenções antrópicas como referência em estudos ecotoxicológicos com organismos terrestres', 'Soils with low human intervention as a reference in ecotoxicological studies with terrestrial organisms'], 'outros-segmentos', C + '3-o-uso-de-solos-com-baixas-intervencoes-antropicas-como-referencia-em-estudos-ecotoxicologicos-com-organismos-terrestres/'],
  [2014, ['Avaliação ecotoxicológica do ecossistema marinho na região de Praia Mole, Espírito Santo', 'Ecotoxicological assessment of the marine ecosystem in the Praia Mole region, Espírito Santo'], 'portos', C + '5-avaliacao-ecotoxicologica-do-ecossistema-marinho-na-regiao-de-praia-mole-espirito-santo-utilizando-organismos-s-costatum-e-lucunter-e-nitokra-sp-em-diferentes-matrizes-ambientais/'],
  [2014, ['Qualidade do sedimento antes, durante e após a disposição do material dragado do Terminal Marítimo de Ubu/ES', 'Sediment quality before, during and after disposal of dredged material from the Ubu Maritime Terminal/ES'], 'portos', C + '7-avaliacao-da-qualidade-do-sedimento-de-uma-area-antes-durante-e-apos-a-disposicao-do-material-dragado-do-terminal-maritimo-de-ubu-es/'],
  [2012, ['Avaliação ecotoxicológica de lagoas internas de um complexo siderúrgico', 'Ecotoxicological assessment of the internal ponds of a steel complex'], 'mineracao-siderurgia-metalurgia', C + '4-avaliacao-ecotoxicologica-de-lagoas-internas-de-um-complexo-siderurgico/'],
  [2012, ['Metodologia para monitoramento ativo de bioacumulação de contaminantes em águas tropicais rasas com exploração e produção', 'Methodology for active monitoring of contaminant bioaccumulation in shallow tropical waters with exploration and production'], 'oleo-e-gas', C + '6-metodologia-para-monitoramento-ativo-de-bioacumulacao-de-contaminantes-em-aguas-tropicais-rasas-com-atividades-de-exploracao-e-producao/'],
  [2008, ['Efeito da condutividade no tratamento biológico de efluente de fábrica de celulose', 'Effect of conductivity on the biological treatment of pulp mill effluent'], 'celulose-e-papel', C + '8-avaliacao-do-efeito-da-condutividade-no-tratamento-biologico-de-uma-efluente-de-uma-fabrica-de-celulose/'],
];

const N = 'https://www.aplysia.com.br/pt/noticias/';
export const noticias = [
  ['2025-08-07', ['Ciência Aplicada: APLYSIA é parceira da UFV na busca pela redução da ecotoxicidade de efluentes industriais', 'Applied Science: APLYSIA partners with UFV to reduce the ecotoxicity of industrial effluents'], ['Estudo publicado na revista Chemosphere propõe caminhos para reduzir a toxicidade crônica de efluentes de celulose e aponta o carvão ativado como opção promissora.', 'A study published in Chemosphere proposes ways to reduce the chronic toxicity of pulp mill effluents and points to activated carbon as a promising option.'], 'noticia-3', N + '155-ciencia-aplicada-aplysia-e-parceira-da-ufv-na-busca-pela-reducao-da-ecotoxicidade-de-efluentes-industriais/'],
  ['2025-08-05', ['Reavaliação concluída com sucesso: Laboratório de Ecotoxicologia da APLYSIA mantém maior número de ensaios acreditados no Brasil', 'Reassessment successfully completed: APLYSIA’s Ecotoxicology Laboratory keeps the largest number of accredited tests in Brazil'], ['O laboratório passou na reavaliação que mantém a acreditação ABNT NBR ISO/IEC 17025.', 'The laboratory passed the reassessment that maintains its ABNT NBR ISO/IEC 17025 accreditation.'], 'noticia-2', N + '153-reavaliacao-concluida-com-sucesso-laboratorio-de-ecotoxicologia-da-aplysia-mantem-maior-numero-de-ensaios-acreditados-no-brasil/'],
  ['2025-05-23', ['Diretora de Inovação da APLYSIA integra o Global Awards Committee da SETAC', 'APLYSIA’s Innovation Director joins SETAC’s Global Awards Committee'], ['A Dra. Tatiana Furley, fundadora e diretora de inovação, foi nomeada representante da América Latina no comitê.', 'Dr. Tatiana Furley, founder and innovation director, was appointed Latin America’s representative on the committee.'], 'noticia-1', N + '149-diretora-de-inovacao-da-aplysia-integra-o-global-awards-committee-da-setac/'],
  ['2025-05-15', ['APLYSIA marca presença no 35º Congresso Anual da SETAC Europa', 'APLYSIA attends the 35th SETAC Europe Annual Meeting'], ['Participação em um dos maiores eventos internacionais de toxicologia e química ambiental.', 'Participation in one of the largest international events on environmental toxicology and chemistry.'], 'noticia-0', N + '147-aplysia-marca-presenca-no-35-congresso-anual-da-setac-europa/'],
  ['', ['Método ReNaturalize é destaque na recuperação do rio Gualaxo do Norte, em Mariana (MG)', 'ReNaturalize method stands out in the recovery of the Gualaxo do Norte river, in Mariana (MG)'], null, 'rio-curso', N + '145-metodo-renaturalize-e-destaque-na-recuperacao-do-rio-gualaxo-do-norte-em-mariana-mg/'],
  ['', ['APLYSIA marca presença no XXV Simpósio Brasileiro de Recursos Hídricos em Aracaju', 'APLYSIA attends the 25th Brazilian Water Resources Symposium in Aracaju'], null, 'rio-amostra', N + '143-aplysia-marca-presenca-no-xxv-simposio-brasileiro-de-recursos-hidricos-em-aracaju/'],
  ['', ['APLYSIA participa do 55º Congresso Internacional de Celulose e Papel, maior evento do setor na América Latina', 'APLYSIA takes part in the 55th International Pulp and Paper Congress, the largest event of the sector in Latin America'], null, 's-ete-startup', N + '141-aplysia-participa-do-55-congresso-internacional-de-celulose-e-papel-maior-evento-do-setor-na-america-latina/'],
  ['', ['APLYSIA apresenta avanços do projeto ReNaturalize no Congresso Internacional de Restauração de Rios, na Inglaterra', 'APLYSIA presents ReNaturalize progress at the International River Restoration Conference, in England'], null, 'rio-trabalho', N + '139-aplysia-apresenta-avancos-do-projeto-renaturalize-no-congresso-internacional-de-restauracao-de-rios-na-inglaterra/'],
];

export const clientes = [
  ['vale', 'Vale'], ['arcelormittal', 'ArcelorMittal'], ['petrobras', 'Petrobras'], ['suzano', 'Suzano'], ['cenibra', 'Cenibra'], ['klabin', 'Klabin'],
  ['gerdau', 'Gerdau'], ['csn', 'CSN'], ['anglo-american', 'Anglo American'], ['samarco', 'Samarco'], ['braskem', 'Braskem'], ['cmpc', 'CMPC'],
  ['veracel', 'Veracel'], ['fibria', 'Fibria'], ['portocel', 'Portocel'], ['arauco', 'Arauco'], ['eldorado', 'Eldorado Brasil'], ['bracell', 'Bracell'],
  ['thyssenkrupp', 'ThyssenKrupp'], ['transpetro', 'Transpetro'], ['mosaic', 'Mosaic'], ['jurong', 'Estaleiro Jurong Aracruz'], ['imetame', 'Imetame'], ['renova', 'Fundação Renova'],
  ['reparacao-rio-doce', 'Reparação Bacia do Rio Doce'], ['cesan', 'Cesan'], ['aegea', 'Aegea'], ['westrock', 'WestRock'], ['mwv-rigesa', 'MWV Rigesa'], ['ld-celulose', 'LD Celulose'],
  ['celulosa-argentina', 'Celulosa Argentina'], ['papel-prensa', 'Papel Prensa'], ['aspen', 'Aspen Pharma'], ['leao', 'Leão Alimentos e Bebidas'], ['buckman', 'Buckman'], ['ashland', 'Ashland'],
  ['brametal', 'Brametal'], ['petrocoque', 'Petrocoque'], ['vitoria-ambiental', 'Vitória Ambiental'], ['sgs', 'SGS'], ['als', 'ALS'], ['merieux', 'Mérieux NutriSciences'],
  ['tommasi', 'Tommasi Laboratório'], ['hydrobiology', 'Hydrobiology'],
];

// Países do mapa "Soluções que atravessam fronteiras" (os mesmos do site atual).
export const paises = { 'Finlândia': 'Finland', 'Canadá': 'Canada', 'Inglaterra': 'England', 'Espanha': 'Spain', 'EUA': 'USA', 'Itália': 'Italy', 'Brasil': 'Brazil', 'Argentina': 'Argentina', 'Austrália': 'Australia', 'Chile': 'Chile' };
