// Tradução para o inglês de cada texto do site da Instor (o site atual tem versão em inglês).
// Nomes de robôs, empresas, contatos e endereços ficam iguais (lista `iguais`).
// Texto novo em conteudo.mjs ou nas versões precisa entrar aqui, senão o gerar.mjs falha.
export const en = {
 "Instor · Robótica móvel para inspeção e operação em áreas de risco": "Instor · Mobile robotics for inspection and operation in hazardous areas",
 "Robôs autônomos e teleoperados para óleo e gás, mineração, logística, agricultura, nuclear e saúde. Engenharia própria desde 2008.": "Autonomous and teleoperated robots for oil and gas, mining, logistics, agriculture, nuclear and health. In-house engineering since 2008.",
 "Robótica a serviço da humanidade": "Robotics at the service of humanity",
 "Olá! Vim pelo site da Instor e gostaria de falar com a equipe.": "Hello! I found the Instor website and would like to talk to the team.",
 "Instor, início": "Instor, home",
 "Projetos &amp; Robótica": "Projects &amp; Robotics",
 "Principal": "Main",
 "Empresa": "About Us",
 "Soluções": "Solutions",
 "Robôs": "Robots",
 "Serviços": "Services",
 "Clientes": "Customers",
 "Imprensa": "News",
 "Contato": "Contact",
 "Fale com a engenharia": "Talk to engineering",
 "Robótica móvel · desde 2008": "Mobile robotics · since 2008",
 "Robôs que vão onde não é seguro mandar pessoas.": "Robots that go where it is not safe to send people.",
 "Reduzir a exposição humana a situações de alto risco e aumentar a eficiência dos processos com robótica móvel. Robôs autônomos e teleoperados projetados e fabricados pela Instor, no Rio Grande do Sul.": "Reduce human exposure to high-risk situations and increase process efficiency through mobile robotics. Autonomous and teleoperated robots designed and built by Instor in Rio Grande do Sul, Brazil.",
 "Conhecer os robôs": "See the robots",
 "Falar com vendas": "Talk to sales",
 "fundada em Porto Alegre, a partir da UFRGS": "founded in Porto Alegre, out of UFRGS",
 "fornecedora cadastrada da Petrobras": "registered Petrobras supplier",
 "robôs próprios desenvolvidos": "in-house robots developed",
 "setores atendidos": "sectors served",
 "Robô Tupã Ex em operação noturna": "Tupã Ex robot in night operation",
 "Primeiro robô autônomo à prova de explosão da América Latina, desenvolvido com a Petrobras.": "The first autonomous explosion-proof robot in Latin America, developed with Petrobras.",
 "Soluções por setor": "Solutions by sector",
 "Seis setores, um mesmo objetivo: tirar a pessoa da área de risco.": "Six sectors, one goal: take people out of the danger zone.",
 "Ver todas as soluções": "See all solutions",
 "Óleo e gás": "Oil and Gas",
 "Robôs autônomos para inspeção de áreas classificadas, com certificação Ex.": "Autonomous robots for inspection of classified areas, with Ex certification.",
 "Mineração": "Mining",
 "Robôs teleoperados para inspeção e transporte em áreas de risco.": "Teleoperated robots for inspection and transport in hazardous areas.",
 "Logística": "Logistics",
 "Robôs autônomos do tipo AMR para movimentação interna.": "Autonomous AMR robots for internal material handling.",
 "Agricultura": "Agriculture",
 "Coleta autônoma de amostras de grãos.": "Autonomous grain sample collection.",
 "Robôs teleoperados para inspeção de áreas perigosas.": "Teleoperated robots for inspection of hazardous areas.",
 "Saúde": "Health",
 "Robôs autônomos para desinfecção de ambientes.": "Autonomous robots for disinfecting environments.",
 "Linha de robôs": "Robot line",
 "Engenharia própria, do chassi ao software.": "In-house engineering, from chassis to software.",
 "Ver os 9 robôs": "See all 9 robots",
 "Inspeção autônoma": "Autonomous inspection",
 "Robô autônomo à prova de explosão para inspeção de rotina em áreas classificadas Zona 1.": "Autonomous explosion-proof robot for routine inspection in Zone 1 classified areas.",
 "Inspeção de tanques": "Tank inspection",
 "Robô hexápode que escala superfícies metálicas para inspecionar tanques.": "Hexapod robot that climbs metal surfaces to inspect tanks.",
 "Desinfecção": "Disinfection",
 "Robô autônomo que combina luz UV-C e névoa ozonizada para desinfetar ambientes.": "Autonomous robot that combines UV-C light and ozonated mist to disinfect environments.",
 "Transporte autônomo": "Autonomous transport",
 "Robô móvel autônomo para logística interna.": "Autonomous mobile robot for internal logistics.",
 "Inspeção térmica": "Thermal inspection",
 "Robô teleoperado com braço articulado para inspeção térmica remota.": "Teleoperated robot with an articulated arm for remote thermal inspection.",
 "Pintura": "Painting",
 "Robô teleoperado para pintura em locais de difícil acesso.": "Teleoperated robot for painting hard-to-reach places.",
 "Linha de robôs da Instor": "Instor robot line",
 "Desenvolvido com quem opera": "Developed with those who operate",
 "Fornecedora cadastrada da Petrobras desde 2012.": "Registered Petrobras supplier since 2012.",
 "O Tupã Ex e o Guaraci nasceram com a Petrobras. O Tupã, com a Vale. O Jaguar e a Jaci, com apoio da Finep. Cada robô sai de um problema real de campo, testado com quem vai usar.": "Tupã Ex and Guaraci were born with Petrobras. Tupã, with Vale. Jaguar and Jaci, with support from Finep. Every robot comes from a real field problem, tested with the people who will use it.",
 "Clientes e parceiros": "Customers and partners",
 "Também operamos os robôs para você.": "We also operate the robots for you.",
 "Ver serviços": "See services",
 "Inspeção robotizada de caldeiras": "Robotic boiler inspection",
 "Inspeção de caldeiras com robô e registro digital de cada ponto medido, sem montar andaime e com a equipe fora do espaço confinado.": "Boiler inspection with a robot and a digital record of every measured point, with no scaffolding and the team kept out of the confined space.",
 "Inspeção de fundo e costado de tanques com o scanner Angoerá e o hexápode Guaraci, inclusive em versão Ex para áreas classificadas.": "Tank floor and shell inspection with the Angoerá scanner and the Guaraci hexapod, including an Ex version for classified areas.",
 "Pintura robotizada": "Robotic painting",
 "O robô Macuxi aplica tinta e revestimento em superfícies de aço carbono em altura, operado à distância pela equipe da Instor.": "The Macuxi robot applies paint and coatings to carbon steel surfaces at height, operated remotely by the Instor team.",
 "Projetos especiais": "Special projects",
 "Quando o robô que resolve o problema ainda não existe, a Instor projeta. Mecânica, eletrônica e software feitos em casa, do estudo de viabilidade ao protótipo em campo.": "When the robot that solves the problem does not exist yet, Instor designs it. Mechanics, electronics and software built in-house, from the feasibility study to the field prototype.",
 "A Instor nas notícias.": "Instor in the news.",
 "Todas as notícias": "All news",
 "Robótica na agricultura: autonomia pode mudar a forma de produção no campo": "Robotics in agriculture: autonomy may change the way farms produce",
 "Ler matéria": "Read article",
 "Embrapa desenvolve robô para a fruticultura": "Embrapa develops a robot for fruit farming",
 "Projeto, robô ou serviço": "Project, robot or service",
 "Conte o ambiente e o risco. A engenharia da Instor indica o robô, ou projeta um.": "Tell us about the environment and the risk. Instor engineering will recommend the robot, or design one.",
 "Falar com a engenharia": "Talk to engineering",
 "WhatsApp de vendas": "Sales WhatsApp",
 "Reduzir a exposição humana a situações de alto risco e aumentar a eficiência dos processos com robótica móvel.": "Reduce human exposure to high-risk situations and increase process efficiency through mobile robotics.",
 "Coletor de Amostras": "Sample Collector",
 "Trabalhe conosco": "Work with us",
 "Vendas (51) 9752-2728": "Sales (51) 9752-2728",
 "© 2026 Instor Projetos e Robótica": "© 2026 Instor Projects and Robotics",
 "Ver as duas versões": "See both versions",
 "Empresa · Instor": "About Us · Instor",
 "Da UFRGS à robótica Ex: a história, a equipe e as políticas da Instor Projetos e Robótica.": "From UFRGS to Ex robotics: the history, team and policies of Instor Projects and Robotics.",
 "Você está em": "You are here",
 "Início": "Home",
 "Da universidade à robótica Ex.": "From the university to Ex robotics.",
 "A Instor nasceu em 2008 de um grupo de estudantes do laboratório de metalurgia da UFRGS. Hoje projeta e fabrica robôs para Petrobras, Vale e grandes indústrias.": "Instor was founded in 2008 by a group of students from the UFRGS metallurgy laboratory. Today it designs and builds robots for Petrobras, Vale and major industries.",
 "Missão": "Mission",
 "Visão": "Vision",
 "Ser referência em robótica móvel de alta qualidade.": "To be a reference in high-quality mobile robotics.",
 "Valores": "Values",
 "Paixão pelo que faz.": "Passion for what we do.",
 "Cada robô nasce de engenharia própria, do projeto mecânico ao software.": "Every robot is born from in-house engineering, from mechanical design to software.",
 "Vontade de vencer desafios.": "Drive to overcome challenges.",
 "Problemas que ninguém resolveu ainda são o ponto de partida dos nossos projetos.": "Problems no one has solved yet are the starting point of our projects.",
 "Inovação fora da caixa.": "Thinking outside the box.",
 "Da inovação incremental à radical, sempre com o pé na operação do cliente.": "From incremental to radical innovation, always grounded in the customer's operation.",
 "Trajetória": "Track record",
 "Mais de vinte anos de robótica.": "More than twenty years of robotics.",
 "Equipe da Instor com um robô na oficina": "Instor team with a robot in the workshop",
 "A equipe da Instor com um dos primeiros robôs.": "The Instor team with one of the first robots.",
 "Os fundadores, ainda estudantes, começam no Laboratório de Metalurgia Física (LAMEF) da Escola de Engenharia da UFRGS.": "The founders, still students, start at the Physical Metallurgy Laboratory (LAMEF) of the UFRGS School of Engineering.",
 "Aprovada na incubadora CEI/UFRGS, a Instor é fundada em julho após estudo de viabilidade técnica e econômica.": "Approved by the CEI/UFRGS incubator, Instor is founded in July after a technical and economic feasibility study.",
 "Entra no programa do Sebrae-RS para a cadeia de óleo, gás e energia do Rio Grande do Sul.": "Joins the Sebrae-RS program for the oil, gas and energy chain of Rio Grande do Sul.",
 "Conquista recursos de inovação em editais da Finep (Prime e Pré-Sal), Sebrae-RS, Senai e Fapergs.": "Wins innovation funding in calls from Finep (Prime and Pre-Salt), Sebrae-RS, Senai and Fapergs.",
 "Gradua-se na incubadora, muda para sede própria e torna-se fornecedora cadastrada da Petrobras.": "Graduates from the incubator, moves to its own headquarters and becomes a registered Petrobras supplier.",
 "Lança o Macuxi, robô de pintura industrial.": "Launches Macuxi, an industrial painting robot.",
 "Desenvolve o Tupã, robô de inspeção térmica, em parceria com a Vale.": "Develops Tupã, a thermal inspection robot, in partnership with Vale.",
 "Entra na robótica Ex com o TUPAEX e lança a Jaci, robô autônomo germicida.": "Enters Ex robotics with TUPAEX and launches Jaci, an autonomous germicidal robot.",
 "Lança o Jaguar AMR para o setor de logística.": "Launches Jaguar AMR for the logistics sector.",
 "Lança o Tupã Ex, robô de esteiras certificado Ex para áreas classificadas, com a Petrobras.": "Launches Tupã Ex, an Ex-certified tracked robot for classified areas, with Petrobras.",
 "Desenvolve o Guaraci, hexápode para inspeção de tanques, com a Petrobras.": "Develops Guaraci, a hexapod for tank inspection, with Petrobras.",
 "Associa-se à SPRINT Robotics e aprova o projeto Hexápode no programa Inovações Radicais para o Setor Elétrico, da Finep.": "Joins SPRINT Robotics and gets the Hexapod project approved in Finep's Radical Innovations for the Electric Sector program.",
 "Torna-se associada da Abendi e aprova os projetos agrícolas Jasuka e Nhandecy.": "Becomes a member of Abendi and gets the Jasuka and Nhandecy agricultural projects approved.",
 "Desenvolve o scanner Angoerá, o Angoerá Ex e a Sonda Ex para prestação de serviços.": "Develops the Angoerá scanner, the Angoerá Ex and the Ex Probe for service work.",
 "Liderança": "Leadership",
 "Quem conduz a Instor.": "Who leads Instor.",
 "Diretora administrativa e cofundadora": "Administrative director and co-founder",
 "Diretor de tecnologia": "Chief technology officer",
 "Diretor de inovação e investidor": "Innovation director and investor",
 "Engenheiros mecânicos, eletrônicos, de controle e automação e de produção, técnicos em eletrônica e mecatrônica e equipe administrativa. A equipe multidisciplinar desenvolve o robô inteiro dentro de casa.": "Mechanical, electronic, control and automation, and production engineers, electronics and mechatronics technicians, and an administrative team. The multidisciplinary team develops the entire robot in-house.",
 "Políticas": "Policies",
 "Qualidade, meio ambiente e segurança.": "Quality, environment and safety.",
 "Qualidade": "Quality",
 "Os parâmetros de qualidade são os requisitos e especificações técnicas de cada cliente. Pesquisas de satisfação orientam a melhoria contínua.": "Quality parameters are each customer's requirements and technical specifications. Satisfaction surveys guide continuous improvement.",
 "Meio ambiente": "Environment",
 "Soluções que não agridem o meio ambiente, prevenção da poluição nos processos e atendimento à legislação ambiental e de segurança do trabalho.": "Solutions that do not harm the environment, pollution prevention in our processes and compliance with environmental and occupational safety legislation.",
 "Saúde e segurança": "Health and safety",
 "Usar a robótica para melhorar a segurança e a saúde das pessoas, eliminando riscos de forma preventiva.": "Using robotics to improve people's safety and health, eliminating risks preventively.",
 "Fornecedora cadastrada Petrobras desde 2012": "Registered Petrobras supplier since 2012",
 "SPRINT Robotics desde 2024": "SPRINT Robotics since 2024",
 "Abendi desde 2025": "Abendi since 2025",
 "Soluções por setor · Instor": "Solutions by sector · Instor",
 "Robôs e serviços da Instor para óleo e gás, mineração, logística, agricultura, nuclear e saúde.": "Instor robots and services for oil and gas, mining, logistics, agriculture, nuclear and health.",
 "Soluções por setor.": "Solutions by sector.",
 "Projetos sob medida para demandas específicas de cada setor, com robôs autônomos ou teleoperados.": "Tailor-made projects for the specific demands of each sector, with autonomous or teleoperated robots.",
 "01 · Óleo e gás": "01 · Oil and Gas",
 "Inspeção de rotina em áreas com risco de explosão, pintura em altura e inspeção de tanques. Os robôs Tupã Ex e Guaraci foram desenvolvidos em parceria com a Petrobras.": "Routine inspection in areas with explosion risk, painting at height and tank inspection. The Tupã Ex and Guaraci robots were developed in partnership with Petrobras.",
 "02 · Mineração": "02 · Mining",
 "Inspeção térmica remota, transporte de carga em espaço confinado e em escadas, longe da exposição do operador. O Tupã foi desenvolvido em parceria com a Vale.": "Remote thermal inspection, load transport in confined spaces and on stairs, away from operator exposure. Tupã was developed in partnership with Vale.",
 "Transporte": "Transport",
 "Veículo elétrico": "Electric vehicle",
 "03 · Logística": "03 · Logistics",
 "O Jaguar AMR navega sozinho entre estações, com lidar, câmeras 3D e paradas de segurança conforme a NR12.": "Jaguar AMR navigates on its own between stations, with lidar, 3D cameras and safety stops in line with NR12.",
 "04 · Agricultura": "04 · Agriculture",
 "Braço autônomo para amostragem de grãos e dois projetos aprovados em 2025, Jasuka e Nhandecy, voltados a pequenas e médias propriedades rurais.": "An autonomous arm for grain sampling and two projects approved in 2025, Jasuka and Nhandecy, aimed at small and medium-sized farms.",
 "Amostragem autônoma": "Autonomous sampling",
 "05 · Nuclear": "05 · Nuclear",
 "Inspeção remota em ambientes onde a presença humana precisa ser evitada, com robôs teleoperados, câmeras e sensores embarcados.": "Remote inspection in environments where human presence must be avoided, with teleoperated robots, cameras and onboard sensors.",
 "06 · Saúde": "06 · Health",
 "A Jaci combina luz UV-C e névoa ozonizada para desinfetar quartos, centros cirúrgicos e áreas de risco de infecção.": "Jaci combines UV-C light and ozonated mist to disinfect rooms, operating theaters and areas at risk of infection.",
 "Robôs · Instor": "Robots · Instor",
 "Conheça os robôs da Instor: Tupã Ex, Macuxi, Guaraci, Tupã, Anhangá, Thor, Jaguar AMR, Coletor de Amostras e Jaci.": "Meet the Instor robots: Tupã Ex, Macuxi, Guaraci, Tupã, Anhangá, Thor, Jaguar AMR, Sample Collector and Jaci.",
 "Robôs Instor.": "Instor robots.",
 "Autônomos e teleoperados, para inspeção, transporte, pintura, amostragem e desinfecção. Todos projetados e fabricados pela Instor.": "Autonomous and teleoperated, for inspection, transport, painting, sampling and disinfection. All designed and built by Instor.",
 "Filtrar por setor": "Filter by sector",
 "Todos": "All",
 "Robô teleoperado de esteiras para transporte de carga em espaços apertados e escadas.": "Teleoperated tracked robot for carrying loads in tight spaces and on stairs.",
 "Veículo elétrico 4x4 para transporte de carga em espaço restrito.": "4x4 electric vehicle for carrying loads in restricted spaces.",
 "Braço autônomo para amostragem de grãos.": "Autonomous arm for grain sampling.",
 "Serviços · Instor": "Services · Instor",
 "Inspeção robotizada de caldeiras e tanques, pintura robotizada e projetos especiais de robótica.": "Robotic inspection of boilers and tanks, robotic painting and special robotics projects.",
 "Serviços com robôs.": "Services with robots.",
 "A Instor leva o robô e a equipe até a sua planta: inspeção, pintura e projetos especiais, com relatório digital ao final.": "Instor brings the robot and the team to your plant: inspection, painting and special projects, with a digital report at the end.",
 "Serviço 01": "Service 01",
 "Medição de espessura e mapeamento de corrosão": "Thickness measurement and corrosion mapping",
 "Imagens e dados georreferenciados por ponto": "Georeferenced images and data for each point",
 "Relatório digital ao final da parada": "Digital report at the end of the shutdown",
 "Pedir proposta": "Request a quote",
 "Serviço 02": "Service 02",
 "Scanner Angoerá e Angoerá Ex": "Angoerá and Angoerá Ex scanner",
 "Sonda Ex para áreas classificadas": "Ex probe for classified areas",
 "Ultrassom embarcado para corrosão": "Onboard ultrasound for corrosion",
 "Serviço 03": "Service 03",
 "Até 200 m² por hora": "Up to 200 m² per hour",
 "Qualquer tinta ou revestimento": "Any paint or coating",
 "Trabalho noturno com iluminação LED": "Night work with LED lighting",
 "Serviço 04": "Service 04",
 "Estudo de viabilidade técnica e econômica": "Technical and economic feasibility study",
 "Projeto mecânico, eletrônico e de software": "Mechanical, electronic and software design",
 "Protótipo, testes em campo e certificação": "Prototype, field tests and certification",
 "Clientes e parceiros · Instor": "Customers and partners · Instor",
 "Empresas, universidades e instituições que trabalham com a Instor.": "Companies, universities and institutions that work with Instor.",
 "Clientes e parceiros.": "Customers and partners.",
 "Empresas, universidades e instituições de fomento que trabalham com a Instor.": "Companies, universities and funding institutions that work with Instor.",
 "Quem já usa robôs Instor.": "Who already uses Instor robots.",
 "Parceiros": "Partners",
 "Pesquisa, fomento e testes.": "Research, funding and testing.",
 "Parceiros comerciais internacionais": "International sales partners",
 "Parceiros comerciais nacionais": "Brazilian sales partners",
 "Imprensa · Instor": "News · Instor",
 "A Instor na imprensa: Petrobras, Finep, Embrapa, Tecnopuc, GZH e outros.": "Instor in the press: Petrobras, Finep, Embrapa, Tecnopuc, GZH and others.",
 "A Instor na imprensa.": "Instor in the press.",
 "Reportagens, artigos e publicações sobre os robôs e projetos da Instor.": "Reports, articles and publications about Instor's robots and projects.",
 "Painel sobre robótica na agricultura no evento Semear Digital": "Panel on robotics in agriculture at the Semear Digital event",
 "Painel de robótica na agricultura, Embrapa Semear Digital, 2026.": "Robotics in agriculture panel, Embrapa Semear Digital, 2026.",
 "Jaguar AMR na edição 144 da EAE Máquinas": "Jaguar AMR in issue 144 of EAE Máquinas",
 "Robô desenvolvido pela Instor será levado para a França": "Robot developed by Instor will be taken to France",
 "Desenvolvemos robô inédito na indústria de óleo e gás da América Latina": "We developed a first-of-its-kind robot for the oil and gas industry in Latin America",
 "Robô inédito para indústria de óleo e gás da América Latina": "First-of-its-kind robot for the oil and gas industry in Latin America",
 "Trabalho pioneiro na UFRGS prevê descontaminação de hospitais com robôs": "Pioneering work at UFRGS plans hospital decontamination with robots",
 "Petrobras divulga startups selecionadas para edital de inovação de R$ 22 milhões": "Petrobras announces startups selected for a R$ 22 million innovation call",
 "Edital da Petrobras seleciona cinco startups gaúchas": "Petrobras call selects five startups from Rio Grande do Sul",
 "Com Jaci, primeiro robô autônomo brasileiro para desinfecção, Instor projeta internacionalização": "With Jaci, the first Brazilian autonomous disinfection robot, Instor plans to go international",
 "Instor lança nova versão autônoma do robô Jaci": "Instor launches a new autonomous version of the Jaci robot",
 "Apoio da Finep viabiliza o primeiro robô autônomo para desinfecção de ambientes da América Latina": "Finep support enables the first autonomous disinfection robot in Latin America",
 "Primeira empresa contratada do edital Tecnologias 4.0 desenvolve projeto de robótica para a indústria": "First company hired under the Technologies 4.0 call develops a robotics project for industry",
 "Instituto de Informática UFRGS": "UFRGS Institute of Informatics",
 "Startup Instor tem projetos em parceria com o INF": "Startup Instor has projects in partnership with INF",
 "Jaci, o robô de desinfecção que auxilia no combate à covid-19": "Jaci, the disinfection robot that helps fight covid-19",
 "Na contramão da crise, empresa porto-alegrense de robótica aposta na inovação": "Against the tide of the crisis, a Porto Alegre robotics company bets on innovation",
 "Empresa de Porto Alegre cria robôs para automatizar tarefas na indústria": "Porto Alegre company creates robots to automate industrial tasks",
 "Limpeza contínua em tubulações": "Continuous pipeline cleaning",
 "Pré-sal": "Pre-salt",
 "Contato · Instor": "Contact · Instor",
 "Fale com a Instor: vendas, compras e financeiro. Matriz em Viamão/RS e filial em Duque de Caxias/RJ.": "Talk to Instor: sales, purchasing and finance. Head office in Viamão/RS and branch in Duque de Caxias/RJ.",
 "Fale com a Instor.": "Talk to Instor.",
 "Conte o que precisa e para onde. A equipe de vendas responde com a solução indicada.": "Tell us what you need and where. The sales team will reply with the recommended solution.",
 "Nome": "Name",
 "E-mail": "Email",
 "Telefone": "Phone",
 "Assunto": "Subject",
 "Quero conhecer um robô": "I want to know a robot",
 "Serviço de inspeção ou pintura": "Inspection or painting service",
 "Projeto especial": "Special project",
 "Compras": "Purchasing",
 "Financeiro": "Finance",
 "Mensagem": "Message",
 "Conte o ambiente, o risco e o que precisa ser feito.": "Describe the environment, the risk and what needs to be done.",
 "Enviar por e-mail": "Send by email",
 "Enviar pelo WhatsApp": "Send via WhatsApp",
 "Vendas": "Sales",
 "Geral": "General",
 "Matriz": "Head office",
 "CEP 94440-000": "ZIP 94440-000",
 "Filial": "Branch",
 "CEP 25011-040": "ZIP 25011-040",
 "Tupã Ex · Inspeção autônoma · Instor": "Tupã Ex · Autonomous inspection · Instor",
 "Primeiro do tipo na América Latina": "First of its kind in Latin America",
 "Solicitar proposta": "Request a quote",
 "Olá! Gostaria de saber mais sobre o Tupã Ex.": "Hello! I would like to know more about Tupã Ex.",
 "O que faz": "What it does",
 "Desenvolvido com a Petrobras, o Tupã Ex percorre rotas programadas em plantas com risco de explosão e faz sozinho a ronda que hoje expõe o operador: mede gases, temperatura, ruído e corrosão, lê instrumentos e procura vazamentos.": "Developed with Petrobras, Tupã Ex follows programmed routes in plants with explosion risk and carries out on its own the inspection round that today exposes the operator: it measures gases, temperature, noise and corrosion, reads instruments and looks for leaks.",
 "Navegação autônoma com rotas programadas e detecção de obstrução em rotas de fuga": "Autonomous navigation with programmed routes and detection of obstructions on escape routes",
 "Detecção de CH4, LEL, H2S, CO e O2 com mapa de concentração": "Detection of CH4, LEL, H2S, CO and O2 with a concentration map",
 "Termografia com histórico por ponto de inspeção": "Thermography with history per inspection point",
 "Câmera OGI para identificar chamas e vazamentos": "OGI camera to identify flames and leaks",
 "Mapeamento 3D e mapa de corrosão em tempo real": "3D mapping and real-time corrosion map",
 "Leitura de etiquetas e instrumentos analógicos e digitais": "Reading of tags and analog and digital instruments",
 "Ficha técnica": "Technical data",
 "Certificação": "Certification",
 "Área": "Area",
 "Zona 1": "Zone 1",
 "Autonomia": "Autonomy",
 "6 horas": "6 hours",
 "Gases": "Gases",
 "Conectividade": "Connectivity",
 "Wi-Fi, 4G LTE e 5G": "Wi-Fi, 4G LTE and 5G",
 "Parceria": "Partnership",
 "Folha de dados completa sob consulta.": "Full datasheet on request.",
 "Veja também": "See also",
 "Outros robôs Instor.": "Other Instor robots.",
 "Todos os robôs": "All robots",
 "Macuxi · Pintura · Instor": "Macuxi · Painting · Instor",
 "Olá! Gostaria de saber mais sobre o Macuxi.": "Hello! I would like to know more about Macuxi.",
 "O Macuxi aplica qualquer tipo de tinta ou revestimento em superfícies de aço carbono, em altura, sem andaime e sem gente pendurada. Também é oferecido pela Instor como serviço de pintura robotizada.": "Macuxi applies any type of paint or coating to carbon steel surfaces, at height, with no scaffolding and no one hanging from ropes. Instor also offers it as a robotic painting service.",
 "Aplica qualquer tipo de tinta ou revestimento": "Applies any type of paint or coating",
 "Trabalha em altura sobre aço carbono": "Works at height on carbon steel",
 "Controle remoto com tela LCD": "Remote control with LCD screen",
 "Iluminação LED para trabalho noturno": "LED lighting for night work",
 "Câmera HD para a operação remota": "HD camera for remote operation",
 "Aplicação": "Application",
 "até 200 m²/h": "up to 200 m²/h",
 "Diâmetro mínimo": "Minimum diameter",
 "Proteção": "Protection",
 "Operação": "Operation",
 "Teleoperado": "Teleoperated",
 "Lançamento": "Launch",
 "Guaraci · Inspeção de tanques · Instor": "Guaraci · Tank inspection · Instor",
 "Olá! Gostaria de saber mais sobre o Guaraci.": "Hello! I would like to know more about Guaraci.",
 "Com seis patas e aderência magnética, o Guaraci anda sobre superfícies complexas e sobe paredes de aço de tanques levando ultrassom para medir corrosão. Em desenvolvimento com a Petrobras.": "With six legs and magnetic adhesion, Guaraci walks over complex surfaces and climbs the steel walls of tanks carrying ultrasound to measure corrosion. Under development with Petrobras.",
 "Locomoção em superfícies complexas": "Locomotion over complex surfaces",
 "Escalada magnética em superfícies ferromagnéticas": "Magnetic climbing on ferromagnetic surfaces",
 "Ultrassom embarcado para inspeção de corrosão": "Onboard ultrasound for corrosion inspection",
 "Iluminação LED": "LED lighting",
 "Relatório de inspeção digital": "Digital inspection report",
 "Alcance sem fio": "Wireless range",
 "até 1 km": "up to 1 km",
 "cerca de 4 horas": "about 4 hours",
 "Tupã · Inspeção térmica · Instor": "Tupã · Thermal inspection · Instor",
 "Olá! Gostaria de saber mais sobre o Tupã.": "Hello! I would like to know more about Tupã.",
 "Desenvolvido em parceria com a Vale, o Tupã leva câmera 4K e sensor térmico na ponta de um braço de cinco graus de liberdade até onde não é seguro mandar uma pessoa, e transmite tudo em tempo real.": "Developed in partnership with Vale, Tupã carries a 4K camera and a thermal sensor at the tip of a five-degree-of-freedom arm to places where it is not safe to send a person, and streams everything in real time.",
 "Câmera PTZ 4K com sensor térmico no braço": "4K PTZ camera with thermal sensor on the arm",
 "Duas câmeras HD na base, frente e traseira": "Two HD cameras on the base, front and rear",
 "Braço articulado de 1.260 mm com 5 graus de liberdade": "1,260 mm articulated arm with 5 degrees of freedom",
 "Tração 4x4 com suspensão independente": "4x4 traction with independent suspension",
 "Umbilical opcional em carretel para resgate": "Optional umbilical on a reel for recovery",
 "Alcance": "Range",
 "até 1 km em área aberta": "up to 1 km in open areas",
 "Velocidade": "Speed",
 "até 9 km/h": "up to 9 km/h",
 "Rampa": "Slope",
 "até 45°": "up to 45°",
 "2 a 10 horas": "2 to 10 hours",
 "Anhangá · Transporte · Instor": "Anhangá · Transport · Instor",
 "Olá! Gostaria de saber mais sobre o Anhangá.": "Hello! I would like to know more about Anhangá.",
 "O Anhangá carrega até 200 kg por corredores estreitos, rampas e escadas, com freio eletromagnético que trava as esteiras em caso de falha, mesmo em inclinação.": "Anhangá carries up to 200 kg through narrow corridors, ramps and stairs, with an electromagnetic brake that locks the tracks in case of failure, even on a slope.",
 "Radar anticolisão com sensores sonar": "Anti-collision radar with sonar sensors",
 "Parada de emergência no controle e nas duas pontas do veículo": "Emergency stop on the controller and at both ends of the vehicle",
 "Freio eletromagnético em rampas de até 35°": "Electromagnetic brake on ramps of up to 35°",
 "Guarda-corpos removíveis e de altura ajustável": "Removable, height-adjustable guardrails",
 "Olhais para içamento e pontos de amarração": "Lifting eyes and tie-down points",
 "Carga": "Payload",
 "Peso": "Weight",
 "Degrau": "Step",
 "até 200 mm": "up to 200 mm",
 "Dimensões": "Dimensions",
 "Thor · Veículo elétrico · Instor": "Thor · Electric vehicle · Instor",
 "Olá! Gostaria de saber mais sobre o Thor.": "Hello! I would like to know more about Thor.",
 "Utilitário 100% elétrico com esterçamento nas quatro rodas: anda de lado, gira no próprio eixo e entra onde um veículo comum não manobra. Pode levar mini guindaste e ser operado à distância.": "A 100% electric utility vehicle with four-wheel steering: it moves sideways, turns on its own axis and gets into places where a regular vehicle cannot maneuver. It can carry a mini crane and be operated remotely.",
 "Tração e esterçamento nas quatro rodas": "Four-wheel drive and steering",
 "Desloca-se de lado ou gira no próprio eixo": "Moves sideways or turns on its own axis",
 "Mini guindaste opcional com patolas eletro-hidráulicas": "Optional mini crane with electro-hydraulic outriggers",
 "Controle remoto completo por joystick": "Full remote control by joystick",
 "Cabine adequada a pessoas com mobilidade reduzida": "Cab suitable for people with reduced mobility",
 "Motorização": "Powertrain",
 "100% elétrica": "100% electric",
 "até 8 horas": "up to 8 hours",
 "Guindaste": "Crane",
 "até 800 kg, giro de 180°": "up to 800 kg, 180° rotation",
 "Tração": "Traction",
 "Suspensão": "Suspension",
 "Independente": "Independent",
 "Jaguar AMR · Transporte autônomo · Instor": "Jaguar AMR · Autonomous transport · Instor",
 "Olá! Gostaria de saber mais sobre o Jaguar AMR.": "Hello! I would like to know more about Jaguar AMR.",
 "O Jaguar leva carga entre estações sem trilho e sem operador. Calcula a rota e desvia de obstáculos em tempo real com lidar, câmeras 3D e odometria. Lançado em 2021, com apoio da Finep.": "Jaguar carries loads between stations with no rails and no operator. It calculates the route and avoids obstacles in real time with lidar, 3D cameras and odometry. Launched in 2021, with support from Finep.",
 "Navegação com lidar, câmeras 3D e odometria": "Navigation with lidar, 3D cameras and odometry",
 "Para-choques, sensores anticolisão e ultrassônicos": "Bumpers, anti-collision and ultrasonic sensors",
 "Comunicação por Wi-Fi, Bluetooth, RFID, QR code e beacons": "Communication via Wi-Fi, Bluetooth, RFID, QR code and beacons",
 "Estação de recarga com ou sem contato": "Charging station with or without contact",
 "Faixa de carga": "Payload range",
 "60 a 1.500 kg": "60 to 1,500 kg",
 "até 3 m/s": "up to 3 m/s",
 "Segurança": "Safety",
 "Apoio": "Support",
 "Coletor de Amostras · Amostragem autônoma · Instor": "Sample Collector · Autonomous sampling · Instor",
 "Olá! Gostaria de saber mais sobre o Coletor de Amostras.": "Hello! I would like to know more about the Sample Collector.",
 "Coleta amostras de grãos de forma rápida, precisa e segura, sem intervenção do operador em nenhuma etapa. Desenvolvido em parceria com a Saur.": "Collects grain samples quickly, accurately and safely, with no operator intervention at any stage. Developed in partnership with Saur.",
 "Amostragem totalmente automática": "Fully automatic sampling",
 "Rapidez e precisão na coleta": "Fast and accurate collection",
 "Operador fora da área de risco": "Operator out of the danger zone",
 "Confiabilidade de operação contínua": "Reliable continuous operation",
 "Autônoma": "Autonomous",
 "Amostragem de grãos": "Grain sampling",
 "Jaci · Desinfecção · Instor": "Jaci · Disinfection · Instor",
 "Primeiro robô autônomo brasileiro de desinfecção": "First Brazilian autonomous disinfection robot",
 "Olá! Gostaria de saber mais sobre o Jaci.": "Hello! I would like to know more about Jaci.",
 "A Jaci percorre o ambiente iluminando as superfícies com UV-C e lança névoa ozonizada nas áreas de sombra. Elimina 99% de vírus e bactérias do ambiente, com menos tempo, menos produto químico e histórico de desinfecção por sala. Testada em cinco hospitais, entre eles o Incor.": "Jaci moves through the room lighting surfaces with UV-C and releases ozonated mist into shaded areas. It eliminates 99% of viruses and bacteria in the environment, with less time, fewer chemicals and a disinfection history for each room. Tested in five hospitals, including Incor.",
 "Emissores UV-C de alta potência": "High-power UV-C emitters",
 "Gerador de névoa ozonizada para ar e superfícies": "Ozonated mist generator for air and surfaces",
 "Torre telescópica de 1,8 m que alcança o teto": "1.8 m telescopic tower that reaches the ceiling",
 "Detecção de pessoas por inteligência artificial": "People detection by artificial intelligence",
 "Acionamento remoto por aplicativo e relatórios por sala": "Remote activation by app and reports for each room",
 "Eficácia": "Effectiveness",
 "99% de vírus e bactérias": "99% of viruses and bacteria",
 "Capacidade": "Capacity",
 "300 m² por hora": "300 m² per hour",
 "Raio de ação": "Range of action",
 "mais de 5 m": "more than 5 m",
 "Torre": "Tower",
 "1,8 m telescópica": "1.8 m telescopic",
 "Fabricação": "Manufacturing",
 "100% nacional": "100% made in Brazil",
 "Finep e Fapergs": "Finep and Fapergs",
 "Fale conosco": "Contact us",
 "Robô Macuxi em operação de pintura": "Macuxi robot in a painting operation",
 "Instor · Projetos &amp; Robótica · Viamão, RS": "Instor · Projects &amp; Robotics · Viamão, RS",
 "Robótica a serviço da humanidade.": "Robotics at the service of humanity.",
 "Ver a frota": "See the fleet",
 "Serviços com robôs": "Services with robots",
 "Setores": "Sectors",
 "Frota Instor": "Instor fleet",
 "Nove robôs projetados e fabricados em casa.": "Nine robots designed and built in-house.",
 "Ficha de cada robô": "Data sheet for each robot",
 "Robô Tupã Ex": "Tupã Ex robot",
 "Em destaque · Óleo e gás": "Featured · Oil and Gas",
 "Tupã Ex. A ronda de inspeção, sem ninguém na Zona 1.": "Tupã Ex. The inspection round, with no one in Zone 1.",
 "de autonomia": "of autonomy",
 "gases detectados": "gases detected",
 "certificação Ex": "Ex certification",
 "Wi-Fi e 4G LTE": "Wi-Fi and 4G LTE",
 "Ficha técnica do Tupã Ex": "Tupã Ex technical data",
 "Onde os robôs Instor trabalham.": "Where Instor robots work.",
 "De um laboratório da UFRGS à robótica certificada Ex.": "From a UFRGS laboratory to Ex-certified robotics.",
 "Sobre a Instor": "About Instor",
 "A equipe Instor opera o robô na sua planta.": "The Instor team operates the robot at your plant.",
 "Quem trabalha com a Instor": "Who works with Instor",
 "Tem uma área onde ninguém deveria entrar?": "Is there an area no one should enter?",
 "Instor Projetos e Robótica. Engenharia e fabricação de robôs móveis desde 2008.": "Instor Projects and Robotics. Engineering and manufacturing of mobile robots since 2008.",
 "Frota": "Fleet",
 "Endereços": "Addresses",
 "Matriz: Av. Sen. Salgado Filho, 7000, sala 276, Jardim Krahe, Viamão/RS": "Head office: Av. Sen. Salgado Filho, 7000, sala 276, Jardim Krahe, Viamão/RS",
 "Filial: Engenho do Porto, Duque de Caxias/RJ": "Branch: Engenho do Porto, Duque de Caxias/RJ",
 "Engenharia própria desde 2008.": "In-house engineering since 2008.",
 "A Instor nasceu de estudantes do Laboratório de Metalurgia Física da UFRGS e hoje desenvolve robôs com Petrobras, Vale e Finep.": "Instor was founded by students from the UFRGS Physical Metallurgy Laboratory and today develops robots with Petrobras, Vale and Finep.",
 "Paixão pelo que faz": "Passion for what we do",
 "Vontade de vencer desafios": "Drive to overcome challenges",
 "Inovação fora da caixa": "Thinking outside the box",
 "Vinte e dois anos, um robô de cada vez.": "Twenty-two years, one robot at a time.",
 "Diretoria.": "Board of directors.",
 "Sistema de gestão": "Management system",
 "Políticas.": "Policies.",
 "Seis setores. Um mesmo objetivo.": "Six sectors. One goal.",
 "Tirar a pessoa da área de risco e deixar o processo mais eficiente, com robôs autônomos ou teleoperados.": "Take people out of the danger zone and make the process more efficient, with autonomous or teleoperated robots.",
 "A frota Instor.": "The Instor fleet.",
 "Inspeção, transporte, pintura, amostragem e desinfecção. Escolha o setor ou abra a ficha técnica de cada robô.": "Inspection, transport, painting, sampling and disinfection. Choose a sector or open each robot's data sheet.",
 "A Instor leva o robô e a equipe até a planta. Inspeção, pintura e projetos especiais, com relatório digital ao final.": "Instor brings the robot and the team to the plant. Inspection, painting and special projects, with a digital report at the end.",
 "Empresas, universidades, hospitais e instituições de fomento que trabalham com a Instor.": "Companies, universities, hospitals and funding institutions that work with Instor.",
 "Parceiros de pesquisa e fomento": "Research and funding partners",
 "Na imprensa.": "In the press.",
 "Reportagens e publicações sobre os robôs e projetos da Instor.": "Reports and publications about Instor's robots and projects.",
 "Conte o ambiente, o risco e o que precisa ser feito. A equipe responde com a solução indicada.": "Describe the environment, the risk and what needs to be done. The team will reply with the recommended solution.",
 "01 · Óleo e gás · Inspeção autônoma": "01 · Oil and Gas · Autonomous inspection",
 "Próximo robô": "Next robot",
 "02 · Óleo e gás · Pintura": "02 · Oil and Gas · Painting",
 "03 · Óleo e gás · Inspeção de tanques": "03 · Oil and Gas · Tank inspection",
 "04 · Mineração · Inspeção térmica": "04 · Mining · Thermal inspection",
 "05 · Mineração · Transporte": "05 · Mining · Transport",
 "06 · Mineração · Veículo elétrico": "06 · Mining · Electric vehicle",
 "07 · Logística · Transporte autônomo": "07 · Logistics · Autonomous transport",
 "08 · Agricultura · Amostragem autônoma": "08 · Agriculture · Autonomous sampling",
 "09 · Saúde · Desinfecção": "09 · Health · Disinfection"
};

export const iguais = new Set([
 "vendas@instor.com.br",
 "LinkedIn",
 "YouTube",
 "instor",
 "Menu",
 "Tupã Ex",
 "Nuclear",
 "Guaraci",
 "Jaci",
 "Jaguar AMR",
 "Tupã",
 "Macuxi",
 "Petrobras",
 "Vale",
 "GE",
 "Braskem",
 "Technip",
 "MKS",
 "Capaz",
 "Araujo",
 "Embrapa Semear Digital · 2026",
 "Grupo Ahora · 2026",
 "Abendi Digital",
 "Anhangá",
 "Thor",
 "Instor",
 "contato@instor.com.br",
 "Av. Sen. Salgado Filho, 7000, sala 276",
 "Jardim Krahe, Viamão/RS",
 "Rua Vicente Apa",
 "Engenho do Porto, Duque de Caxias/RJ",
 "Miguel Ignacio Serrano",
 "CEO",
 "Marta Von Dentz",
 "Diógenes Casagrande",
 "Luciano Eifler",
 "Geremia",
 "Triel",
 "PUCRS",
 "Unicamp",
 "UFRJ",
 "UFRGS",
 "Finep",
 "Fapergs",
 "Sebrae",
 "Unisinos",
 "USP",
 "Hospital Sírio-Libanês",
 "InovaIncor",
 "Premiere Hospital",
 "Ericsson",
 "Conceptmed",
 "Cyberia",
 "AFI Robotics",
 "Technip Energies",
 "SNEF",
 "Al Maseela",
 "Suppress",
 "PRK",
 "Revista EAE Máquinas",
 "Tecnopuc",
 "TN Petróleo",
 "GZH · 2022",
 "TI Inside · 2021",
 "Guaíba · 2021",
 "Instituto Caldeira",
 "Tecnopuc · 2020",
 "Jornal do Comércio · 2020",
 "Jornal do Comércio · 2018",
 "Jornal do Comércio · 2016",
 "Revista Veja · 2012",
 "(51) 9752-2728 · WhatsApp",
 "compras@instor.com.br",
 "(51) 99477-1412 · WhatsApp",
 "financeiro@instor.com.br",
 "(51) 99872-1613 · WhatsApp",
 "gerencia@instor.com.br",
 "WhatsApp",
 "Ex db ib pxb h IIB T3 Gb",
 "CH4, LEL, H2S, CO, O2",
 "14 m",
 "IP65",
 "IP66",
 "200 kg",
 "300 kg",
 "2 km/h",
 "1200 × 600 × 410 mm",
 "4x4",
 "NR12",
 "Saur",
 "6 h",
 "5G",
 "Embrapa Semear Digital",
 "Grupo Ahora",
 "GZH",
 "TI Inside",
 "Guaíba",
 "Jornal do Comércio",
 "Revista Veja"
]);
