// Textos do site do Grupo Toniolo em português, inglês e espanhol.
// O site atual (grupotoniolo.com) tem seletor "Idioma" no topo, então o novo também tem as três línguas.
// Textos em português vêm do site atual; os números são os da página Quem Somos.
export const T = (pt, en, es) => ({ pt, en, es });
export const tr = (x, l) => (x && typeof x === 'object' && 'pt' in x ? x[l] : x);

export const LANGS = ['pt', 'en', 'es'];
export const LANG = {
  pt: { nome: 'Português', curto: 'PT', html: 'pt-BR', og: 'pt_BR' },
  en: { nome: 'English', curto: 'EN', html: 'en', og: 'en_US' },
  es: { nome: 'Español', curto: 'ES', html: 'es', og: 'es_ES' },
};

export const site = {
  nome: 'Grupo Toniolo',
  dominio: 'https://toniolo.overtus.com.br',
  fundacao: 1980,
  cidade: 'Colombo/PR',
  telPrincipal: '(41) 99256-0901',
  telPrincipalHref: '+5541992560901',
  email: 'contato@grupotoniolo.com',
  whatsapp: '5541992560901',
  redes: [
    ['Facebook', 'https://www.facebook.com/grupotoniolo'],
    ['Instagram', 'https://www.instagram.com/grupotoniololtda'],
    ['LinkedIn', 'https://www.linkedin.com/company/grupo-toniolo'],
    ['YouTube', 'https://www.youtube.com/tmjterraplanagem'],
  ],
  linkedin: 'https://www.linkedin.com/company/grupo-toniolo',
  curriculo: 'https://grupotoniolo.com/cadastro-de-curriculo/',
  manual: 'https://grupotoniolo.com/manual-do-colaborador/',
  catalogo: 'https://grupotoniolo.com/catalogo/',
  video: 'fKygBIRDE0Y',
};

export const departamentos = [
  [T('Comercial', 'Sales', 'Comercial'), ['(41) 99256-0901', '(41) 99135-9813'], 'comercial@grupotoniolo.com'],
  [T('Contratos e financeiro', 'Contracts and finance', 'Contratos y finanzas'), ['(41) 99195-1296'], 'contato@grupotoniolo.com'],
  [T('Recursos humanos', 'Human resources', 'Recursos humanos'), ['(41) 99133-0786', '(41) 99246-8639'], 'rh@grupotoniolo.com'],
  [T('Compras', 'Purchasing', 'Compras'), ['(41) 3656-1134'], 'compras@grupotoniolo.com'],
];

// Páginas: [slug, nome no menu, título da aba, descrição]
export const paginas = {
  index: [T('Home', 'Home', 'Inicio'), T('Grupo Toniolo · Soluções em rejeitos, barragens e dragagem', 'Grupo Toniolo · Tailings, dam and dredging solutions', 'Grupo Toniolo · Soluciones en relaves, presas y dragado'),
    T('Desde 1980 em Colombo/PR. Manejo e remanejo de rejeitos com escavadeiras anfíbias patenteadas, descaracterização de barragens, desaguamento, dragagem e empilhamento a seco.',
      'Since 1980 in Colombo, Paraná, Brazil. Tailings management with patented amphibious excavators, dam decharacterization, dewatering, dredging and dry stacking.',
      'Desde 1980 en Colombo, Paraná, Brasil. Manejo de relaves con excavadoras anfibias patentadas, descaracterización de presas, desaguado, dragado y apilamiento en seco.')],
  'quem-somos': [T('Quem somos', 'About us', 'Quiénes somos'), T('Quem somos · Grupo Toniolo', 'About us · Grupo Toniolo', 'Quiénes somos · Grupo Toniolo'),
    T('A história pioneira do Grupo Toniolo, iniciada em 1980 em Colombo/PR: missão, visão, valores, certificação ISO 9001 e números de atuação.',
      'The pioneering story of Grupo Toniolo, started in 1980 in Colombo, Paraná: mission, vision, values, ISO 9001 certification and key figures.',
      'La historia pionera del Grupo Toniolo, iniciada en 1980 en Colombo, Paraná: misión, visión, valores, certificación ISO 9001 y cifras.')],
  solucoes: [T('Soluções', 'Solutions', 'Soluciones'), T('Soluções · Grupo Toniolo', 'Solutions · Grupo Toniolo', 'Soluciones · Grupo Toniolo'),
    T('Nove soluções para mineração, barragens e corpos d’água: rejeitos, descaracterização, desaguamento, dragagem, empilhamento a seco, correias, macrófitas e remoção mecanizada.',
      'Nine solutions for mining, dams and water bodies: tailings, decharacterization, dewatering, dredging, dry stacking, conveyor belts, macrophytes and mechanized removal.',
      'Nueve soluciones para minería, presas y cuerpos de agua: relaves, descaracterización, desaguado, dragado, apilamiento en seco, cintas, macrófitas y remoción mecanizada.')],
  carreira: [T('Trabalhe conosco', 'Careers', 'Trabaje con nosotros'), T('Trabalhe conosco · Grupo Toniolo', 'Careers · Grupo Toniolo', 'Trabaje con nosotros · Grupo Toniolo'),
    T('Junte-se à equipe do Grupo Toniolo: cadastre seu currículo, consulte o Manual do Colaborador e acompanhe as vagas no LinkedIn.',
      'Join the Grupo Toniolo team: submit your résumé, read the Employee Manual and follow our openings on LinkedIn.',
      'Únase al equipo del Grupo Toniolo: registre su currículum, consulte el Manual del Colaborador y siga las vacantes en LinkedIn.')],
  blog: [T('Blog', 'Blog', 'Blog'), T('Blog · Grupo Toniolo', 'Blog · Grupo Toniolo', 'Blog · Grupo Toniolo'),
    T('Artigos técnicos do Grupo Toniolo sobre escavadeira anfíbia, desassoreamento, descaracterização de barragens, empilhamento a seco e dragagem.',
      'Technical articles by Grupo Toniolo on amphibious excavators, desilting, dam decharacterization, dry stacking and dredging.',
      'Artículos técnicos del Grupo Toniolo sobre excavadora anfibia, desazolve, descaracterización de presas, apilamiento en seco y dragado.')],
  transparencia: [T('Transparência e igualdade salarial', 'Pay transparency', 'Transparencia salarial'), T('Transparência e igualdade salarial · Grupo Toniolo', 'Pay transparency and equality · Grupo Toniolo', 'Transparencia e igualdad salarial · Grupo Toniolo'),
    T('Relatório de Transparência Salarial e o compromisso do Grupo Toniolo com a igualdade salarial e a valorização das pessoas.',
      'Pay Transparency Report and Grupo Toniolo’s commitment to equal pay and to valuing people.',
      'Informe de Transparencia Salarial y el compromiso del Grupo Toniolo con la igualdad salarial y la valoración de las personas.')],
  contato: [T('Contato', 'Contact', 'Contacto'), T('Contato · Grupo Toniolo', 'Contact · Grupo Toniolo', 'Contacto · Grupo Toniolo'),
    T('Fale com o comercial, contratos e financeiro, RH ou compras do Grupo Toniolo. Telefones, e-mails e formulário.',
      'Contact Grupo Toniolo sales, contracts and finance, HR or purchasing. Phones, e-mails and form.',
      'Hable con el área comercial, contratos y finanzas, RR. HH. o compras del Grupo Toniolo. Teléfonos, correos y formulario.')],
};

export const menu = ['index', 'quem-somos', 'solucoes', 'blog', 'transparencia', 'contato'];

// As nove soluções, na ordem do menu do site atual.
export const solucoes = [
  {
    id: 'manejo-e-remanejo-de-rejeitos', foto: 'sol-manejo', foto2: 'anfibia-reservatorio', icone: 0,
    nome: T('Manejo e remanejo de rejeitos', 'Tailings management and relocation', 'Manejo y reubicación de relaves'),
    resumo: T('Reorganização do rejeito dentro da própria barragem com escavadeiras anfíbias patenteadas.', 'Reorganizing tailings inside the dam itself with patented amphibious excavators.', 'Reorganización del relave dentro de la propia presa con excavadoras anfibias patentadas.'),
    texto: [
      T('O serviço de manejo e remanejo de rejeitos em mineradoras é uma prática essencial para garantir a segurança, sustentabilidade e conformidade ambiental das operações de mineração. Envolve a gestão eficiente dos resíduos sólidos gerados durante o processo de beneficiamento mineral, visando minimizar os impactos ambientais e os riscos para as comunidades próximas.',
        'Tailings management and relocation at mining companies is an essential practice to ensure the safety, sustainability and environmental compliance of mining operations. It involves the efficient management of the solid waste generated during mineral processing, aiming to minimize environmental impacts and risks to nearby communities.',
        'El servicio de manejo y reubicación de relaves en mineras es una práctica esencial para garantizar la seguridad, la sostenibilidad y el cumplimiento ambiental de las operaciones mineras. Implica la gestión eficiente de los residuos sólidos generados durante el beneficio mineral, con el fin de minimizar los impactos ambientales y los riesgos para las comunidades cercanas.'),
      T('O serviço de manejo e remanejo de rejeitos dentro de reservatórios consiste na reorganização do rejeito dentro da própria barragem, fazendo com que os novos rejeitos a serem depositados ocupem locais que não ocupariam sem que seja feito o seu direcionamento através de leiras defletoras e canais direcionais para tais pontos. Ainda, é possível elevar o ângulo de disposição do rejeito no reservatório.',
        'Tailings management inside reservoirs consists of reorganizing the tailings within the dam itself, so that new tailings are deposited in places they would not reach without being directed there by deflector berms and directional channels. It is also possible to raise the disposal angle of the tailings in the reservoir.',
        'El manejo y reubicación de relaves dentro de embalses consiste en reorganizar el relave dentro de la propia presa, de modo que los nuevos relaves ocupen lugares que no ocuparían sin ser dirigidos mediante bermas deflectoras y canales direccionales. Además, es posible elevar el ángulo de disposición del relave en el embalse.'),
      T('Para a realização deste serviço são necessárias escavadeiras anfíbias capazes de operar sobre lâminas de água e sobre rejeitos não adensados. O Grupo Toniolo possui a patente de escavadeiras anfíbias no Brasil, com equipamentos operados manualmente e remotamente controlados, e desenvolveu um sistema de segurança que informa qualquer entrada de água nos flutuantes, prevenindo acidentes com equipamentos e colaboradores.',
        'This service requires amphibious excavators able to operate on water and on unthickened tailings. Grupo Toniolo holds the patent for amphibious excavators in Brazil, with manually operated and remote-controlled units, and developed a safety system that reports any water entering the floats, preventing accidents with equipment and staff.',
        'Para este servicio se necesitan excavadoras anfibias capaces de operar sobre láminas de agua y sobre relaves no espesados. El Grupo Toniolo posee la patente de excavadoras anfibias en Brasil, con equipos de operación manual y control remoto, y desarrolló un sistema de seguridad que avisa cualquier entrada de agua en los flotadores, previniendo accidentes con equipos y colaboradores.'),
    ],
    ganhos: [
      T('Ocupação otimizada até a máxima capacidade de armazenamento', 'Storage used up to its maximum capacity', 'Ocupación optimizada hasta la máxima capacidad de almacenamiento'),
      T('Adiamento de alteamentos e de novos reservatórios', 'Postponed dam raisings and new reservoirs', 'Aplazamiento de recrecimientos y de nuevos embalses'),
      T('Maior estabilidade do rejeito', 'Greater tailings stability', 'Mayor estabilidad del relave'),
      T('Expulsão da água contida na polpa', 'Water expelled from the pulp', 'Expulsión del agua contenida en la pulpa'),
    ],
  },
  {
    id: 'estabilidade-e-descaracterizacao-de-barragens', foto: 'sol-estabilidade', foto2: 'descaracterizacao', icone: 1,
    nome: T('Estabilidade e descaracterização de barragens', 'Dam stability and decharacterization', 'Estabilidad y descaracterización de presas'),
    resumo: T('Remoção controlada de rejeitos, nova geometria e drenagem para estruturas mais seguras.', 'Controlled tailings removal, new geometry and drainage for safer structures.', 'Remoción controlada de relaves, nueva geometría y drenaje para estructuras más seguras.'),
    texto: [
      T('A estabilidade e a descaracterização de barragens são fundamentais para a gestão de resíduos e para a segurança das comunidades vizinhas. A descaracterização refere-se à remoção total ou parcial da barragem; a estabilidade é a capacidade da estrutura de manter sua integridade em condições adversas.',
        'Dam stability and decharacterization are essential for waste management and for the safety of neighboring communities. Decharacterization means the total or partial removal of the dam; stability is the structure’s ability to keep its integrity under adverse conditions.',
        'La estabilidad y la descaracterización de presas son fundamentales para la gestión de residuos y la seguridad de las comunidades vecinas. La descaracterización se refiere a la remoción total o parcial de la presa; la estabilidad es la capacidad de la estructura de mantener su integridad en condiciones adversas.'),
      T('Manter uma barragem segura exige avaliação contínua da estabilidade do solo, das condições hidrológicas, da capacidade de carga e da integridade estrutural. A descaracterização é um processo controlado que reduz os riscos da operação contínua: envolve a remoção gradual dos rejeitos, a reconfiguração da geometria da barragem e a instalação de sistemas de drenagem que limitam o acúmulo de água.',
        'Keeping a dam safe requires continuous assessment of soil stability, hydrological conditions, load capacity and structural integrity. Decharacterization is a controlled process that lowers the risks of continued operation: it involves gradually removing tailings, reshaping the dam’s geometry and installing drainage systems that limit water buildup.',
        'Mantener una presa segura exige evaluar de forma continua la estabilidad del suelo, las condiciones hidrológicas, la capacidad de carga y la integridad estructural. La descaracterización es un proceso controlado que reduce los riesgos de la operación continua: implica retirar gradualmente los relaves, reconfigurar la geometría de la presa e instalar sistemas de drenaje que limitan la acumulación de agua.'),
      T('Remover ou realocar grandes volumes de rejeito e alterar o terreno pode afetar a hidrologia e os ecossistemas locais, por isso os rejeitos removidos são tratados e dispostos com segurança e os impactos são avaliados e mitigados com planejamento e gestão ambiental. O Grupo Toniolo já realizou diversos projetos de estabilidade e descaracterização com equipamentos especializados.',
        'Removing or relocating large volumes of tailings and changing the terrain can affect local hydrology and ecosystems, so removed tailings are treated and disposed of safely and impacts are assessed and mitigated through planning and environmental management. Grupo Toniolo has completed many stability and decharacterization projects with specialized equipment.',
        'Retirar o reubicar grandes volúmenes de relave y alterar el terreno puede afectar la hidrología y los ecosistemas locales, por eso los relaves retirados se tratan y disponen con seguridad y los impactos se evalúan y mitigan con planificación y gestión ambiental. El Grupo Toniolo ya realizó diversos proyectos de estabilidad y descaracterización con equipos especializados.'),
    ],
    ganhos: [
      T('Escavadeiras anfíbias', 'Amphibious excavators', 'Excavadoras anfibias'),
      T('Dragas de sucção e recalque', 'Suction and discharge dredges', 'Dragas de succión e impulsión'),
      T('Escavadeiras de lança longa', 'Long-reach excavators', 'Excavadoras de brazo largo'),
      T('Sistemas de drenagem', 'Drainage systems', 'Sistemas de drenaje'),
    ],
    ganhosTitulo: T('Equipamentos empregados', 'Equipment used', 'Equipos empleados'),
  },
  {
    id: 'desaguamento-de-rejeitos', foto: 'sol-desaguamento', foto2: 'desaguamento', icone: 2,
    nome: T('Desaguamento de rejeitos', 'Tailings dewatering', 'Desaguado de relaves'),
    resumo: T('Aceleramento mecanizado do adensamento do rejeito, com reaproveitamento da água.', 'Mechanized acceleration of tailings thickening, with water reuse.', 'Aceleración mecanizada del espesamiento del relave, con reutilización del agua.'),
    texto: [
      T('O desaguamento retira o excesso de água dos rejeitos sólidos e gera um material mais seco e estável, mais fácil de manusear, transportar e dispor. Reduz o volume, diminui o risco de deslizamentos e colapsos e permite reaproveitar a água recuperada em processos industriais.',
        'Dewatering removes excess water from solid tailings and produces a drier, more stable material that is easier to handle, transport and dispose of. It reduces volume, lowers the risk of slides and collapses and allows the recovered water to be reused in industrial processes.',
        'El desaguado retira el exceso de agua de los relaves sólidos y genera un material más seco y estable, más fácil de manipular, transportar y disponer. Reduce el volumen, disminuye el riesgo de deslizamientos y colapsos y permite reutilizar el agua recuperada en procesos industriales.'),
      T('Em reservatórios ou baias de rejeito, o desaguamento é técnica e economicamente viável para altas taxas de disposição e grandes reservatórios, podendo reduzir a necessidade de equipamentos de filtragem, com custos de implantação e operação menores que a filtragem. Consiste no aceleramento mecanizado do adensamento do rejeito, com vibração ou movimentação de equipamentos, tempo de operação e canais de drenagem.',
        'In tailings reservoirs or bays, dewatering is technically and economically viable for high disposal rates and large reservoirs, and can reduce the need for filtration equipment, with lower implementation and operating costs than filtration. It consists of mechanically accelerating tailings thickening through equipment vibration or movement, operating time and drainage channels.',
        'En embalses o bahías de relaves, el desaguado es técnica y económicamente viable para altas tasas de disposición y grandes embalses, y puede reducir la necesidad de equipos de filtrado, con costos de implantación y operación menores que el filtrado. Consiste en acelerar mecánicamente el espesamiento del relave mediante vibración o movimiento de equipos, tiempo de operación y canales de drenaje.'),
      T('A operação contínua depende de um planejamento por etapas, e o Grupo Toniolo dispõe de uma linha de equipamentos dedicada ao desaguamento.',
        'Continuous operation depends on staged planning, and Grupo Toniolo has a line of equipment dedicated to dewatering.',
        'La operación continua depende de una planificación por etapas, y el Grupo Toniolo dispone de una línea de equipos dedicada al desaguado.'),
    ],
    etapas: [
      T('Área recebendo rejeito', 'Area receiving tailings', 'Área recibiendo relave'),
      T('Desaguamento inicial', 'Initial dewatering', 'Desaguado inicial'),
      T('Desaguamento intermediário', 'Intermediate dewatering', 'Desaguado intermedio'),
      T('Desaguamento final', 'Final dewatering', 'Desaguado final'),
      T('Remoção do rejeito', 'Tailings removal', 'Remoción del relave'),
    ],
  },
  {
    id: 'dragagem-por-succao-e-recalque', foto: 'sol-succao', foto2: 'dragagem', icone: 3,
    nome: T('Dragagem por sucção e recalque', 'Suction and discharge dredging', 'Dragado por succión e impulsión'),
    resumo: T('Dragas, motobombas e bombas dimensionadas para a vazão de cada projeto de remoção.', 'Dredges, motor pumps and pumps sized for the flow of each removal project.', 'Dragas, motobombas y bombas dimensionadas para el caudal de cada proyecto.'),
    texto: [
      T('A dragagem por sucção e recalque é um método amplamente utilizado para remover sedimentos de corpos d’água como rios, lagos, portos e canais. Uma draga equipada com bomba de sucção aspira os sólidos e a polpa líquida e os transporta por tubulações até as áreas designadas.',
        'Suction and discharge dredging is a widely used method to remove sediment from water bodies such as rivers, lakes, ports and canals. A dredge fitted with a suction pump draws in solids and liquid slurry and carries them through pipelines to the designated areas.',
        'El dragado por succión e impulsión es un método muy utilizado para retirar sedimentos de cuerpos de agua como ríos, lagos, puertos y canales. Una draga equipada con bomba de succión aspira los sólidos y la pulpa líquida y los transporta por tuberías hasta las áreas designadas.'),
      T('O método mantém os canais de navegação na profundidade necessária, evita o assoreamento e contribui para a prevenção de enchentes e para a eficiência portuária. Equipamentos adequados e manutenção regular são essenciais.',
        'The method keeps navigation channels at the required depth, prevents silting and helps prevent floods and improve port efficiency. Proper equipment and regular maintenance are essential.',
        'El método mantiene los canales de navegación en la profundidad necesaria, evita la sedimentación y contribuye a prevenir inundaciones y a la eficiencia portuaria. Los equipos adecuados y el mantenimiento regular son esenciales.'),
      T('O Grupo Toniolo possui dragas, motobombas e bombas de diversos modelos, dimensionadas para as vazões utilizadas em projetos de remoção de rejeitos.',
        'Grupo Toniolo has dredges, motor pumps and pumps in several models, sized for the flow rates used in tailings removal projects.',
        'El Grupo Toniolo posee dragas, motobombas y bombas de diversos modelos, dimensionadas para los caudales utilizados en proyectos de remoción de relaves.'),
    ],
    ganhos: [
      T('Canais na profundidade necessária', 'Channels at the required depth', 'Canales en la profundidad necesaria'),
      T('Prevenção do assoreamento', 'Silting prevention', 'Prevención de la sedimentación'),
      T('Apoio à prevenção de enchentes', 'Support for flood prevention', 'Apoyo a la prevención de inundaciones'),
      T('Transporte por tubulação até a área de destino', 'Pipeline transport to the destination area', 'Transporte por tubería hasta el área de destino'),
    ],
  },
  {
    id: 'dragagem-de-precisao', foto: 'sol-precisao', foto2: 'anfibia-margem', icone: 4,
    nome: T('Dragagem de precisão', 'Precision dredging', 'Dragado de precisión'),
    resumo: T('Escavadeira anfíbia com bomba de dragagem e desagregador: alto teor de sólidos e baixa turbidez.', 'Amphibious excavator with dredge pump and disaggregator: high solids, low turbidity.', 'Excavadora anfibia con bomba de dragado y desagregador: alto contenido de sólidos y baja turbidez.'),
    texto: [
      T('A dragagem de precisão é uma técnica avançada de remoção de sedimentos em corpos d’água, valorizada pela exatidão em áreas sensíveis ou de difícil acesso, onde a remoção excessiva poderia prejudicar a fauna, a flora e a qualidade da água.',
        'Precision dredging is an advanced technique for removing sediment from water bodies, valued for its accuracy in sensitive or hard-to-reach areas, where excessive removal could harm wildlife, vegetation and water quality.',
        'El dragado de precisión es una técnica avanzada de remoción de sedimentos en cuerpos de agua, valorada por su exactitud en áreas sensibles o de difícil acceso, donde una remoción excesiva podría perjudicar la fauna, la flora y la calidad del agua.'),
      T('Ela ajuda a otimizar portos, marinas e outras infraestruturas hídricas, mantém canais de navegação e áreas portuárias na profundidade adequada e contribui para recuperar lagos, rios e zonas costeiras degradados.',
        'It helps optimize ports, marinas and other water infrastructure, keeps navigation channels and port areas at the right depth and helps restore degraded lakes, rivers and coastal zones.',
        'Ayuda a optimizar puertos, marinas y otras infraestructuras hídricas, mantiene canales de navegación y áreas portuarias en la profundidad adecuada y contribuye a recuperar lagos, ríos y zonas costeras degradados.'),
      T('O Grupo Toniolo utiliza uma escavadeira anfíbia equipada com uma bomba de dragagem de alta potência e um desagregador de material em sua extremidade, permitindo uma performance de alto teor de sólidos e baixa turbidez na água. As operações são guiadas por tecnologia avançada de mapeamento do leito.',
        'Grupo Toniolo uses an amphibious excavator fitted with a high-power dredge pump and a material disaggregator at its tip, delivering high solids content and low water turbidity. Operations are guided by advanced bed-mapping technology.',
        'El Grupo Toniolo utiliza una excavadora anfibia equipada con una bomba de dragado de alta potencia y un desagregador de material en su extremo, lo que permite un alto contenido de sólidos y baja turbidez en el agua. Las operaciones se guían con tecnología avanzada de mapeo del lecho.'),
    ],
    ganhos: [
      T('Alto teor de sólidos', 'High solids content', 'Alto contenido de sólidos'),
      T('Baixa turbidez na água', 'Low water turbidity', 'Baja turbidez del agua'),
      T('Mapeamento do leito', 'Bed mapping', 'Mapeo del lecho'),
      T('Atuação em áreas sensíveis', 'Work in sensitive areas', 'Actuación en áreas sensibles'),
    ],
  },
  {
    id: 'secagem-e-empilhamento-a-seco', foto: 'sol-empilhamento', foto2: 'empilhamento', icone: 5,
    nome: T('Secagem e empilhamento a seco', 'Drying and dry stacking', 'Secado y apilamiento en seco'),
    resumo: T('Dry Stacking: do desaguamento à pilha de rejeito (PDR), com até 95% da água reaproveitada.', 'Dry Stacking: from dewatering to the tailings stack, reusing up to 95% of the water.', 'Dry Stacking: del desaguado a la pila de relaves, con hasta 95% del agua reutilizada.'),
    texto: [
      T('O empilhamento a seco de rejeitos é uma técnica de gestão de resíduos, usada principalmente na mineração, que reduz a água presente no rejeito. Mais seco, o rejeito fica mais estável, tem menos risco de vazamentos e deslizamentos e é mais fácil de dispor.',
        'Dry stacking of tailings is a waste management technique, used mainly in mining, that reduces the water in the tailings. Drier tailings are more stable, carry less risk of leaks and slides and are easier to dispose of.',
        'El apilamiento en seco de relaves es una técnica de gestión de residuos, usada principalmente en minería, que reduce el agua presente en el relave. Más seco, el relave es más estable, tiene menos riesgo de fugas y deslizamientos y es más fácil de disponer.'),
      T('O rejeito desaguado é disposto em uma pilha de rejeito (PDR) com menor umidade, o que melhora a compactação. Diferente das barragens de rejeito, não precisa de água para construir a estrutura de contenção, e permite um reaproveitamento de até 95% da água.',
        'Dewatered tailings are placed in a tailings stack with lower moisture, which improves compaction. Unlike tailings dams, it needs no water to build the containment structure, and it allows up to 95% of the water to be reused.',
        'El relave desaguado se dispone en una pila de relaves con menor humedad, lo que mejora la compactación. A diferencia de las presas de relaves, no necesita agua para construir la estructura de contención y permite reutilizar hasta el 95% del agua.'),
      T('O Grupo Toniolo executa todo o processo: remoção, desaguamento, secagem e empilhamento controlado em PDR conforme o projeto. É a solução Dry Stacking, uma tendência crescente entre as mineradoras brasileiras pela segurança que oferece.',
        'Grupo Toniolo runs the whole process: removal, dewatering, drying and controlled stacking according to the design. This is the Dry Stacking solution, a growing trend among Brazilian miners because of the safety it provides.',
        'El Grupo Toniolo ejecuta todo el proceso: remoción, desaguado, secado y apilamiento controlado según el proyecto. Es la solución Dry Stacking, una tendencia creciente entre las mineras brasileñas por la seguridad que ofrece.'),
    ],
    etapas: [
      T('Remoção', 'Removal', 'Remoción'),
      T('Desaguamento', 'Dewatering', 'Desaguado'),
      T('Secagem', 'Drying', 'Secado'),
      T('Empilhamento em PDR', 'Stacking', 'Apilamiento'),
    ],
  },
  {
    id: 'limpeza-mecanizada-de-transportadores-de-correia', foto: 'sol-sabre', foto2: 'sabre', icone: 6,
    nome: T('Limpeza mecanizada de transportadores de correia', 'Mechanized conveyor belt cleaning', 'Limpieza mecanizada de cintas transportadoras'),
    resumo: T('Implemento Sabre: limpeza sob a correia sem trabalho manual e sem parar o transportador.', 'Sabre attachment: cleaning under the belt with no manual work and no conveyor stop.', 'Implemento Sabre: limpieza bajo la cinta sin trabajo manual y sin detener el transportador.'),
    texto: [
      T('A limpeza de transportadores de correia é essencial na mineração para a eficiência operacional, a prevenção de acidentes e a qualidade do produto. Correias limpas reduzem perdas de material, diminuem o desgaste de componentes, evitam contaminação e duram mais, o que reduz custos com substituições e reparos.',
        'Conveyor belt cleaning is essential in mining for operational efficiency, accident prevention and product quality. Clean belts reduce material losses, cut component wear, avoid contamination and last longer, which lowers replacement and repair costs.',
        'La limpieza de cintas transportadoras es esencial en minería para la eficiencia operativa, la prevención de accidentes y la calidad del producto. Las cintas limpias reducen pérdidas de material, disminuyen el desgaste de componentes, evitan contaminación y duran más, lo que reduce costos de reemplazo y reparación.'),
      T('Para substituir o trabalho manual nessa tarefa, o Grupo Toniolo desenvolveu o implemento Sabre, acoplado a uma escavadeira de pequeno porte. Ele arrasta o sedimento depositado sob a correia até um ponto de carregamento, sem expor a estrutura do transportador a riscos.',
        'To replace manual work in this task, Grupo Toniolo developed the Sabre attachment, mounted on a small excavator. It drags the sediment deposited under the belt to a loading point, without putting the conveyor structure at risk.',
        'Para sustituir el trabajo manual en esta tarea, el Grupo Toniolo desarrolló el implemento Sabre, acoplado a una excavadora pequeña. Arrastra el sedimento depositado bajo la cinta hasta un punto de carga, sin exponer la estructura del transportador a riesgos.'),
    ],
    ganhos: [
      T('Opera nos sentidos vertical e horizontal', 'Works vertically and horizontally', 'Opera en sentido vertical y horizontal'),
      T('Acessa locais restritos', 'Reaches restricted spaces', 'Accede a lugares restringidos'),
      T('Não exige parar o transportador', 'No need to stop the conveyor', 'No exige detener el transportador'),
      T('Sem trabalho manual sob a correia', 'No manual work under the belt', 'Sin trabajo manual bajo la cinta'),
    ],
  },
  {
    id: 'remocao-de-macrofitas', foto: 'sol-macrofitas', foto2: 'macrofitas', icone: 7,
    nome: T('Remoção de macrófitas', 'Macrophyte removal', 'Remoción de macrófitas'),
    resumo: T('Escavadeira anfíbia com implementos para cortar e recolher vegetação, galhos e troncos.', 'Amphibious excavator with attachments to cut and collect vegetation, branches and logs.', 'Excavadora anfibia con implementos para cortar y recoger vegetación, ramas y troncos.'),
    texto: [
      T('A retirada de macrófitas (plantas aquáticas), galhos e troncos de rios, lagos e córregos ajuda a manter a qualidade da água e protege o habitat aquático. Obstruções por detritos podem aumentar o risco de enchentes em chuvas fortes, e a remoção também limita o acúmulo de sedimentos e nutrientes.',
        'Removing macrophytes (aquatic plants), branches and logs from rivers, lakes and streams helps keep water quality and protects aquatic habitat. Debris blockages can raise flood risk during heavy rain, and removal also limits the buildup of sediment and nutrients.',
        'La retirada de macrófitas (plantas acuáticas), ramas y troncos de ríos, lagos y arroyos ayuda a mantener la calidad del agua y protege el hábitat acuático. Las obstrucciones por residuos pueden aumentar el riesgo de inundaciones con lluvias fuertes, y la remoción también limita la acumulación de sedimentos y nutrientes.'),
      T('O Grupo Toniolo já executou esse trabalho no Rio Tibagi, no Paraná, e em um rio que atravessa Itabirito, em Minas Gerais, utilizando escavadeira anfíbia com implementos para cortar e recolher galhos e troncos.',
        'Grupo Toniolo has done this work on the Tibagi River in Paraná and on a river that crosses Itabirito, Minas Gerais, using an amphibious excavator with attachments to cut and collect branches and logs.',
        'El Grupo Toniolo ya realizó este trabajo en el río Tibagi, en Paraná, y en un río que atraviesa Itabirito, en Minas Gerais, utilizando excavadora anfibia con implementos para cortar y recoger ramas y troncos.'),
    ],
    ganhos: [
      T('Qualidade da água preservada', 'Water quality preserved', 'Calidad del agua preservada'),
      T('Menor risco de enchentes', 'Lower flood risk', 'Menor riesgo de inundaciones'),
      T('Menos acúmulo de sedimentos', 'Less sediment buildup', 'Menos acumulación de sedimentos'),
      T('Rio Tibagi (PR) e Itabirito (MG)', 'Tibagi River (PR) and Itabirito (MG)', 'Río Tibagi (PR) e Itabirito (MG)'),
    ],
  },
  {
    id: 'remocao-mecanizada', foto: 'sol-remocao', foto2: 'lanca-longa', icone: 8,
    nome: T('Remoção mecanizada', 'Mechanized removal', 'Remoción mecanizada'),
    resumo: T('Equipamentos especiais com lança de até 25 metros e a maior capacidade de carga do Brasil.', 'Special equipment with booms up to 25 metres and the largest load capacity in Brazil.', 'Equipos especiales con brazo de hasta 25 metros y la mayor capacidad de carga de Brasil.'),
    texto: [
      T('A remoção mecanizada tem um papel fundamental na mineração em geral e na gestão de resíduos, principalmente em terrenos acidentados ou de difícil acesso, onde a remoção com lança longa permite movimentar material com segurança.',
        'Mechanized removal plays a key role in mining and waste management, especially on rough or hard-to-reach ground, where long-reach removal allows material to be moved safely.',
        'La remoción mecanizada tiene un papel fundamental en la minería en general y en la gestión de residuos, sobre todo en terrenos accidentados o de difícil acceso, donde la remoción con brazo largo permite mover material con seguridad.'),
      T('O Grupo Toniolo possui equipamentos convencionais e especiais para obras de pequeno, médio e grande porte. O transporte é planejado conforme tempo, tipo de solo e distância, com caminhões ou sistemas não convencionais para grandes volumes.',
        'Grupo Toniolo has conventional and special equipment for small, medium and large jobs. Transport is planned according to time, soil type and distance, using trucks or non-conventional systems for large volumes.',
        'El Grupo Toniolo posee equipos convencionales y especiales para obras pequeñas, medianas y grandes. El transporte se planifica según tiempo, tipo de suelo y distancia, con camiones o sistemas no convencionales para grandes volúmenes.'),
      T('Suas escavadeiras especiais têm lanças com alcance de até 25 metros e a maior capacidade de carga do Brasil, o que reduz o número de acessos necessários dentro da área de remoção.',
        'Its special excavators have booms reaching up to 25 metres and the largest load capacity in Brazil, which reduces the number of access routes needed inside the removal area.',
        'Sus excavadoras especiales tienen brazos con alcance de hasta 25 metros y la mayor capacidad de carga de Brasil, lo que reduce la cantidad de accesos necesarios dentro del área de remoción.'),
    ],
    etapas: [
      T('Drenagem e adensamento com escavadeiras anfíbias', 'Drainage and thickening with amphibious excavators', 'Drenaje y espesamiento con excavadoras anfibias'),
      T('Construção dos acessos', 'Building access routes', 'Construcción de los accesos'),
      T('Carregamento com escavadeiras especiais', 'Loading with special excavators', 'Carga con excavadoras especiales'),
      T('Transporte planejado', 'Planned transport', 'Transporte planificado'),
    ],
  },
];

// Números da página Quem Somos do site atual.
export const numeros = [
  ['1980', T('fundação em Colombo/PR', 'founded in Colombo, Paraná', 'fundación en Colombo, Paraná')],
  ['+75', T('barragens mantidas em operação no Brasil', 'dams kept in operation in Brazil', 'presas mantenidas en operación en Brasil')],
  ['+500 mi m³', T('de movimentação interna de rejeitos', 'of internal tailings movement', 'de movimiento interno de relaves')],
  ['+12', T('paralisações drásticas de plantas evitadas', 'drastic plant shutdowns avoided', 'paradas drásticas de plantas evitadas')],
  ['-80%', T('de emissões frente aos métodos tradicionais', 'emissions versus traditional methods', 'de emisiones frente a métodos tradicionales')],
];

export const historia = [
  T('Fazer do negócio uma referência nacional e internacional no seu segmento, tornando-se uma empresa aliada ao meio ambiente e comprometida com clientes, fornecedores e colaboradores. Assim se fundamenta a história pioneira do Grupo Toniolo, iniciada em 1980, no município de Colombo, no estado do Paraná.',
    'To make the business a national and international reference in its field, becoming a company allied with the environment and committed to clients, suppliers and employees. This is the foundation of Grupo Toniolo’s pioneering story, which began in 1980 in the town of Colombo, in the state of Paraná.',
    'Hacer del negocio una referencia nacional e internacional en su segmento, convirtiéndose en una empresa aliada del medio ambiente y comprometida con clientes, proveedores y colaboradores. Así se fundamenta la historia pionera del Grupo Toniolo, iniciada en 1980 en el municipio de Colombo, en el estado de Paraná.'),
  T('Sempre se adaptando às necessidades e transformações deste competitivo mercado, a empresa dedica seus anos de existência a buscar soluções criativas para desenvolver seu trabalho, personalizando suas ações, produtos e serviços. Desenvolvemos técnicas únicas e exclusivas, sendo a mais conhecida o remanejo de rejeitos com o auxílio das escavadeiras anfíbias patenteadas, que permitiu a várias barragens o aumento de segurança e de vida útil.',
    'Always adapting to the needs and changes of this competitive market, the company has spent its years looking for creative solutions, tailoring its actions, products and services. We have developed unique, exclusive techniques, the best known being tailings relocation with our patented amphibious excavators, which has given many dams more safety and a longer service life.',
    'Siempre adaptándose a las necesidades y transformaciones de este mercado competitivo, la empresa dedica sus años de existencia a buscar soluciones creativas, personalizando sus acciones, productos y servicios. Desarrollamos técnicas únicas y exclusivas, la más conocida es la reubicación de relaves con las excavadoras anfibias patentadas, que permitió a varias presas aumentar su seguridad y su vida útil.'),
  T('Com a técnica desenvolvida, a ocupação de rejeito na barragem é controlada e planejada, garantindo a qualidade da água e aumentando a estabilidade mecânica dos rejeitos, o que permitiu que em nenhuma barragem em que passamos entrasse em nível de segurança.',
    'With this technique, tailings placement in the dam is controlled and planned, ensuring water quality and increasing the mechanical stability of the tailings, so that no dam we have worked on has ever entered a safety alert level.',
    'Con la técnica desarrollada, la ocupación del relave en la presa es controlada y planificada, garantizando la calidad del agua y aumentando la estabilidad mecánica de los relaves, lo que permitió que ninguna presa en la que trabajamos entrara en nivel de seguridad.'),
];

export const missao = T('Gerar riqueza e bem-estar para o Brasil e para a sociedade, aprimorando a extração de recursos naturais com eficiência e cuidado com o meio ambiente.',
  'To generate wealth and well-being for Brazil and society by improving the extraction of natural resources with efficiency and care for the environment.',
  'Generar riqueza y bienestar para Brasil y la sociedad, mejorando la extracción de recursos naturales con eficiencia y cuidado del medio ambiente.');
export const visao = T('Ser a melhor empresa da América Latina em movimentação de terra, água e recursos minerais, com alcance global e foco em inovação tecnológica.',
  'To be the best company in Latin America at moving earth, water and mineral resources, with global reach and a focus on technological innovation.',
  'Ser la mejor empresa de América Latina en movimiento de tierra, agua y recursos minerales, con alcance global y enfoque en la innovación tecnológica.');
export const valores = [
  T('Amor', 'Love', 'Amor'), T('Adaptabilidade', 'Adaptability', 'Adaptabilidad'), T('Humildade', 'Humility', 'Humildad'), T('Caráter', 'Character', 'Carácter'),
  T('Determinação', 'Determination', 'Determinación'), T('Competência', 'Competence', 'Competencia'), T('Confiança', 'Trust', 'Confianza'), T('Inovação', 'Innovation', 'Innovación'),
  T('Processos', 'Processes', 'Procesos'), T('Excelência', 'Excellence', 'Excelencia'), T('Cooperação', 'Cooperation', 'Cooperación'), T('Educação', 'Education', 'Educación'),
  T('Sabedoria', 'Wisdom', 'Sabiduría'), T('Satisfação', 'Satisfaction', 'Satisfacción'), T('Trabalho', 'Hard work', 'Trabajo'), T('Valor', 'Value', 'Valor'),
];

// Logos de clientes do site atual (nome do arquivo em assets/clientes/, nome da empresa).
export const clientes = [
  ['anglo-american', 'Anglo American'], ['vale', 'Vale'], ['csn', 'CSN'], ['mosaic', 'Mosaic Fertilizantes'], ['usiminas', 'Mineração Usiminas'], ['anglogold', 'AngloGold Ashanti'], ['cmoc', 'CMOC'],
  ['cr-almeida', 'CR Almeida'], ['estre', 'Estre'], ['grupo-aterpa', 'Grupo Aterpa'], ['inb', 'INB'], ['jmaluceli', 'JMalucelli'], ['kinross', 'Kinross Paracatu'],
  ['odebrecht', 'Odebrecht'], ['pref-itabirito', 'Prefeitura de Itabirito'], ['sanepar', 'Sanepar'], ['santo-antonio', 'Santo Antônio Energia'], ['tibagi', 'Tibagi Energia'],
  ['vetria', 'Vetria Mineração'], ['neoenergia', 'Neoenergia'], ['nexa', 'Nexa'],
];

// Artigos mais recentes do blog atual (os links abrem o artigo no site atual).
export const blog = [
  ['desaguamento-rejeitos-empilhamento-a-seco', 'arte-desaguamento', '05/10/2026', T('Desaguamento de rejeitos e empilhamento a seco: etapas, diferenças e aplicações', 'Tailings dewatering and dry stacking: stages, differences and applications', 'Desaguado de relaves y apilamiento en seco: etapas, diferencias y aplicaciones')],
  ['escavadeira-anfibia-como-funciona', 'arte-anfibia', '28/09/2026', T('Escavadeira anfíbia: como funciona e quando utilizar em áreas alagadas', 'Amphibious excavator: how it works and when to use it in flooded areas', 'Excavadora anfibia: cómo funciona y cuándo usarla en áreas inundadas')],
  ['desassoreamento-de-reservatorios', 'arte-desassoreamento', '17/09/2026', T('Desassoreamento de reservatórios: métodos, equipamentos e planejamento técnico', 'Reservoir desilting: methods, equipment and technical planning', 'Desazolve de embalses: métodos, equipos y planificación técnica')],
  ['descaracterizacao-de-barragens', 'arte-descaracterizacao', '24/08/2026', T('Descaracterização de barragens: etapas, métodos construtivos e responsabilidade técnica', 'Dam decharacterization: stages, construction methods and technical responsibility', 'Descaracterización de presas: etapas, métodos constructivos y responsabilidad técnica')],
  ['macrofitas-aquaticas-reservatorios', 'arte-macrofitas', '14/08/2026', T('Macrófitas aquáticas em reservatórios: impacto hidráulico e protocolo de remoção mecanizada', 'Aquatic macrophytes in reservoirs: hydraulic impact and mechanized removal protocol', 'Macrófitas acuáticas en embalses: impacto hidráulico y protocolo de remoción mecanizada')],
  ['empilhamento-a-seco-o-futuro-da-disposicao-de-rejeitos-na-mineracao-brasileira', 'arte-empilhamento', '11/06/2026', T('Empilhamento a seco: o futuro da disposição de rejeitos na mineração brasileira', 'Dry stacking: the future of tailings disposal in Brazilian mining', 'Apilamiento en seco: el futuro de la disposición de relaves en la minería brasileña')],
  ['escavadeira-anfibia-principios-tecnicos-e-aplicacoes-em-interface-terra-agua', 'arte-interface', '24/04/2026', T('Escavadeira anfíbia: princípios técnicos e aplicações em interface terra-água', 'Amphibious excavator: technical principles and land-water applications', 'Excavadora anfibia: principios técnicos y aplicaciones en la interfaz tierra-agua')],
  ['passo-a-passo-de-uma-dragagem-mecanizada-eficiente', 'arte-dragagem', '06/04/2026', T('Passo a passo de uma dragagem mecanizada eficiente', 'Step by step of efficient mechanized dredging', 'Paso a paso de un dragado mecanizado eficiente')],
  ['sabre-a-tecnologia-que-redefine-a-limpeza-mecanizada-de-correias-transportadoras', 'arte-sabre', '03/11/2025', T('SABRE: a tecnologia que redefine a limpeza mecanizada de correias transportadoras', 'SABRE: the technology redefining mechanized conveyor belt cleaning', 'SABRE: la tecnología que redefine la limpieza mecanizada de cintas transportadoras')],
];

// Textos de interface.
export const ui = {
  idioma: T('Idioma', 'Language', 'Idioma'),
  menu: T('Menu', 'Menu', 'Menú'),
  saibaMais: T('Saiba mais', 'Learn more', 'Más información'),
  heroTitulo: T('Somos uma empresa de soluções', 'We are a solutions company', 'Somos una empresa de soluciones'),
  heroSub: T('Rejeitos, barragens e corpos d’água: engenharia de campo com escavadeiras anfíbias patenteadas, desde 1980.', 'Tailings, dams and water bodies: field engineering with patented amphibious excavators, since 1980.', 'Relaves, presas y cuerpos de agua: ingeniería de campo con excavadoras anfibias patentadas, desde 1980.'),
  verSolucoes: T('Ver as soluções', 'See our solutions', 'Ver las soluciones'),
  falarComercial: T('Falar com o comercial', 'Talk to sales', 'Hablar con el comercial'),
  quemSomos: T('Quem somos', 'About us', 'Quiénes somos'),
  oGrupo: T('O Grupo Toniolo', 'Grupo Toniolo', 'El Grupo Toniolo'),
  clientes: T('Clientes', 'Clients', 'Clientes'),
  clientesSub: T('Mineradoras, construtoras, saneamento e energia confiam nas nossas equipes.', 'Mining, construction, sanitation and energy companies trust our teams.', 'Mineras, constructoras, saneamiento y energía confían en nuestros equipos.'),
  solucoes: T('Soluções', 'Solutions', 'Soluciones'),
  solucoesSub: T('Nove frentes de trabalho para mineração, barragens e corpos d’água.', 'Nine fields of work for mining, dams and water bodies.', 'Nueve frentes de trabajo para minería, presas y cuerpos de agua.'),
  plus: T('Conhecer', 'Explore', 'Conocer'),
  carreira: T('Carreira', 'Careers', 'Carrera'),
  carreiraTexto: T('Estamos sempre em busca de pessoas comprometidas, que queiram crescer com a gente em obras de mineração, barragens e saneamento em todo o Brasil.', 'We are always looking for committed people who want to grow with us on mining, dam and sanitation projects across Brazil.', 'Siempre buscamos personas comprometidas que quieran crecer con nosotros en obras de minería, presas y saneamiento en todo Brasil.'),
  junteSe: T('Junte-se à nossa equipe', 'Join our team', 'Únase a nuestro equipo'),
  vagasLinkedin: T('Vagas abertas no LinkedIn', 'Open positions on LinkedIn', 'Vacantes en LinkedIn'),
  cadastreCurriculo: T('Cadastre seu currículo', 'Submit your résumé', 'Registre su currículum'),
  manual: T('Manual do Colaborador', 'Employee Manual', 'Manual del Colaborador'),
  contato: T('Contato', 'Contact', 'Contacto'),
  contatoSub: T('Fale direto com a área certa. Respondemos por telefone, WhatsApp ou e-mail.', 'Reach the right department directly. We answer by phone, WhatsApp or e-mail.', 'Hable directo con el área correcta. Respondemos por teléfono, WhatsApp o correo.'),
  formNome: T('Nome', 'Name', 'Nombre'), formEmpresa: T('Empresa', 'Company', 'Empresa'), formEmail: T('E-mail', 'E-mail', 'Correo'),
  formTel: T('Telefone', 'Phone', 'Teléfono'), formAssunto: T('Assunto', 'Subject', 'Asunto'), formMsg: T('Mensagem', 'Message', 'Mensaje'),
  formEnviar: T('Enviar mensagem', 'Send message', 'Enviar mensaje'),
  formOrcamento: T('Orçamento', 'Quote', 'Presupuesto'), formTrabalhe: T('Trabalhe conosco', 'Careers', 'Trabaje con nosotros'), formOutro: T('Outro assunto', 'Other', 'Otro asunto'),
  atuacao: T('Atuação em todo o Brasil', 'Operations across Brazil', 'Actuación en todo Brasil'),
  atuacaoTexto: T('Equipes e equipamentos mobilizados em obras de Norte a Sul do país, a partir da sede em Colombo/PR.', 'Teams and equipment deployed on projects from north to south of the country, from our base in Colombo, Paraná.', 'Equipos y maquinaria movilizados en obras de norte a sur del país, desde la sede en Colombo, Paraná.'),
  missao: T('Missão', 'Mission', 'Misión'), visao: T('Visão', 'Vision', 'Visión'), valores: T('Valores', 'Values', 'Valores'),
  iso: T('Certificação ISO 9001', 'ISO 9001 certified', 'Certificación ISO 9001'),
  isoTexto: T('Processos de gestão da qualidade certificados.', 'Certified quality management processes.', 'Procesos de gestión de calidad certificados.'),
  premio: T('Destaque em Segurança', 'Safety Highlight', 'Destacado en Seguridad'),
  premioTexto: T('Prêmio Fornecedores de Destaque 2021 da Anglo American, Minério de Ferro.', 'Anglo American Outstanding Suppliers Award 2021, Iron Ore.', 'Premio Proveedores Destacados 2021 de Anglo American, Mineral de Hierro.'),
  patente: T('Patente nacional', 'National patent', 'Patente nacional'),
  patenteTexto: T('Escavadeiras anfíbias patenteadas, operadas manualmente ou por controle remoto.', 'Patented amphibious excavators, manually operated or remote-controlled.', 'Excavadoras anfibias patentadas, de operación manual o por control remoto.'),
  assistirVideo: T('Assistir ao vídeo', 'Watch the video', 'Ver el video'),
  outrasSolucoes: T('Outras soluções', 'Other solutions', 'Otras soluciones'),
  ganhos: T('O que a solução entrega', 'What it delivers', 'Lo que entrega la solución'),
  etapas: T('Como funciona', 'How it works', 'Cómo funciona'),
  orcamentoTitulo: T('Tem um projeto de rejeitos, barragem ou dragagem?', 'Do you have a tailings, dam or dredging project?', '¿Tiene un proyecto de relaves, presas o dragado?'),
  orcamentoTexto: T('Nossa equipe comercial avalia o caso e indica a solução e os equipamentos.', 'Our sales team reviews the case and recommends the solution and equipment.', 'Nuestro equipo comercial evalúa el caso e indica la solución y los equipos.'),
  whatsapp: T('WhatsApp', 'WhatsApp', 'WhatsApp'),
  lerArtigo: T('Ler artigo', 'Read article', 'Leer artículo'),
  blogSub: T('Conteúdo técnico sobre rejeitos, barragens, dragagem e equipamentos especiais.', 'Technical content on tailings, dams, dredging and special equipment.', 'Contenido técnico sobre relaves, presas, dragado y equipos especiales.'),
  blogTodos: T('Ver todos os artigos', 'See all articles', 'Ver todos los artículos'),
  catalogo: T('Catálogo 2026', 'Catalog 2026', 'Catálogo 2026'),
  transpTitulo: T('Transparência e igualdade salarial', 'Pay transparency and equality', 'Transparencia e igualdad salarial'),
  transpTexto: [
    T('O Grupo Toniolo mantém o compromisso com a igualdade salarial e com a valorização das pessoas, em um ambiente de trabalho justo, que reconhece talentos diversos.', 'Grupo Toniolo is committed to equal pay and to valuing people, in a fair workplace that recognizes diverse talent.', 'El Grupo Toniolo mantiene el compromiso con la igualdad salarial y la valoración de las personas, en un ambiente de trabajo justo que reconoce talentos diversos.'),
    T('Em atendimento à legislação trabalhista brasileira (Lei 14.611/2023), publicamos periodicamente o Relatório de Transparência Salarial e de Critérios Remuneratórios.', 'In compliance with Brazilian labor law (Law 14,611/2023), we periodically publish the Pay Transparency and Remuneration Criteria Report.', 'En cumplimiento de la legislación laboral brasileña (Ley 14.611/2023), publicamos periódicamente el Informe de Transparencia Salarial y Criterios Remunerativos.'),
  ],
  relatorio: T('Relatório de Transparência Salarial', 'Pay Transparency Report', 'Informe de Transparencia Salarial'),
  compromisso: T('Compromisso com a igualdade salarial', 'Commitment to equal pay', 'Compromiso con la igualdad salarial'),
  abrirDocumento: T('Abrir documento', 'Open document', 'Abrir documento'),
  direitos: T('Todos os direitos reservados.', 'All rights reserved.', 'Todos los derechos reservados.'),
  verVersoes: T('Ver as duas versões', 'See both versions', 'Ver las dos versiones'),
  inicio: T('Início', 'Home', 'Inicio'),
  voceEsta: T('Você está em', 'You are here', 'Usted está en'),
  departamentos: T('Departamentos', 'Departments', 'Departamentos'),
  enviePor: T('Envie sua mensagem', 'Send us a message', 'Envíe su mensaje'),
  sede: T('Sede em Colombo, Paraná', 'Headquarters in Colombo, Paraná', 'Sede en Colombo, Paraná'),
  links: T('Navegação', 'Navigation', 'Navegación'),
  redes: T('Redes sociais', 'Social media', 'Redes sociales'),
  todas: T('Todas as soluções', 'All solutions', 'Todas las soluciones'),
  pioneira: T('Pioneira no Brasil em soluções com escavadeira anfíbia', 'Pioneer in Brazil in amphibious excavator solutions', 'Pionera en Brasil en soluciones con excavadora anfibia'),
  emNumeros: T('Em números', 'In numbers', 'En números'),
  waMsg: T('Olá! Vim pelo site do Grupo Toniolo e gostaria de falar com o comercial.', 'Hello! I found the Grupo Toniolo website and would like to talk to sales.', '¡Hola! Vi el sitio del Grupo Toniolo y me gustaría hablar con el área comercial.'),
};
